Preprocessing

In [1]:
import pandas as pd

df_glossary = pd.read_csv("glossary_all.csv")
df_glossary = df_glossary[["zh-CN", "ko"]].dropna()
df_glossary["zh-CN_length"] = df_glossary["zh-CN"].str.len()
df_glossary = df_glossary.sort_values("zh-CN_length", ascending=False)
df_glossary = df_glossary.drop('zh-CN_length', axis=1)
df_glossary

C:\Users\Longtukorea\AppData\Local\Temp\ipykernel_48076\2563788696.py:3: DtypeWarning: Columns (1,2,3,4,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_glossary = pd.read_csv("glossary_all.csv")

,zh-CN,ko
21702,不管在什么时候，你都是一个打不倒的女汉子。在事业的领域，你是一个非常有自己想法的人，同时你所...,당신은 언제나 여장부 같은 모습입니다. 사업 분야에서 당신은 자신만의 생각을 가진 ...
10132,钟力低声道“师父只说摩云派应将至宝让与其他门派的前辈。可这江湖千门百派，为何无人与咱们相让？...,종력이 낮은 목소리로 말했습니다. [사부님께선 마운파가 기보를 다른 문파에게 양보해...
21683,"你是一个风趣幽默,且正能量满满的人。你大大咧咧的性格让你显得特别单纯，让人特别像捏几下你可爱...",당신은 재미있고 에너지가 넘치는 사람입니다. 활발한 성격으로 인해 단순해 보이게 합...
21693,或许你的外表会给人一种难以靠近的距离。你虽然有些高冷，让别人总是觉得你难以接近，但其实你的内...,당신의 차가움 때문에 다른 사람들이 쉽게 다가가지 못하지만 사실 당신의 마음은 열정...
56075,中秋宴俗. 明代宫廷时兴吃螃蟹。螃蟹用蒲包蒸熟后，众人围坐品尝，佐以酒醋。食毕饮苏叶汤，并用...,추석연회. 명대 궁중에서는 게가 유행했다. 게를 부들포에 싸서 삶은 후 여럿이 모여...
...,...,...
92677,礼,선물
95145,典,축제
62451,甲,갑옷
73240,阶,단계
63642,五,5

In [2]:
glossary_dict = {index: {"zh-CN": row["zh-CN"], "ko": row["ko"]} for index, row in df_glossary.iterrows()}
glossary_dict

{21702: {'zh-CN': '不管在什么时候，你都是一个打不倒的女汉子。在事业的领域，你是一个非常有自己想法的人，同时你所坚持的事情也一定能够梦想成真；你从不轻言放弃，你的这股子干劲儿自然是让你看起来更像一个男人的特质。而身为一个女性，你在很多时候也会表现出对家务活的钟爱，特别是能够勤劳一些，把家庭打扫的干净，里里外外都整理的有条不紊，都是你很喜欢的事情。但在更多时候，你还是希望能在事业上闯出一番天地，你的性格很强势，但在心爱的人面前你也会有小鸟依人的一面，更多数时候别人看到的是你外表的那种热情，但你的小女人只留给心爱的人罢了。',
  'ko': '당신은 언제나 여장부 같은 모습입니다. 사업 분야에서 당신은 자신만의 생각을 가진 사람으로 원하는 일을 반드시 이룰 수 있습니다. 여성으로서 당신은 집안일을 게을리하지 않고 부지런하게 청결을 유지합니다. 그러나 더 많은 경우에 당신은 여전히 사업에서 한 단계 도약하기를 원하고 성격이 매우 강인하여 다른 사람 앞에서 열정적인 모습으로 남게 될 것입니다.'},
 10132: {'zh-CN': '钟力低声道“师父只说摩云派应将至宝让与其他门派的前辈。可这江湖千门百派，为何无人与咱们相让？！”. 钟震无奈的对爱徒摇了摇头“力儿你用剑，应该知道宝剑锋芒两刃，运用不当伤人亦会伤己啊……”. 钟力心有不甘，但贤孝的他并没有当面顶撞自己的师父，只是小声嘀咕道“只要是兵器，哪有能百分百确定不伤己的呢…”. 次日，摩云派因怀藏八至宝中的火龙刀而被武林正邪两派怨妒，遭到围攻，满门无一幸免。除了当年号称‘少云剑’的摩云大弟子——今天的‘血妖’钟力。',
  'ko': '종력이 낮은 목소리로 말했습니다. [사부님께선 마운파가 기보를 다른 문파에게 양보해야 한다고 하셨습니다. 하지만 강호에 이렇게 많은 문파가 있는데 왜 그 누구도 우리에겐 양보하지 않는 겁니까?!]. 종진은 제자를 보고 고개를 저었습니다. [력아, 너도 검을 써보았으니 알겠지만 검은 잘못하면 자신을 다치게 할수도 있단다.] . 종력은 여전히 납득하지 못했지만 충실한 제자인 그는 사부에게 맞서지 않았습니다. 다만 작은 목소리로 [무기라면 모두 자신을 해칠수도 있지 않은가...]라고 중얼 거렸습니다.  .  다음날, 마운파는 팔대기보 중 화룡도를 가지고 있다는 이유로 무림 정사파의 질투를 사 멸문하게 되었습니다. [소운검]이라고 불리던 마운파 제자 종력만 빼고...'},
 21683: {'zh-CN': '你是一个风趣幽默,且正能量满满的人。你大大咧咧的性格让你显得特别单纯，让人特别像捏几下你可爱的脸蛋!一点心机都没有，内心十分善良,是喜是悲全写在脸上。说话不喜欢拐弯抹角，有什么就说什么,也容易让人猜懂你的心事。任何人跟你在一起都会觉得十分自在没有什么压力，也因为你人畜无害的性格，所以你的身边也会聚集一大批两肋插刀的朋友。当妹纸面对这么一个天真可爱的男生时，怎能不偷偷喜欢上你呢！',
  'ko': '당신은 재미있고 에너지가 넘치는 사람입니다. 활발한 성격으로 인해 단순해 보이게 합니다. 당신은 매우 친절하며 모든 감정이 얼굴에 드러납니다. 말을 빙빙 돌려서 하는 것을 싫어하고, 있는 대로 말하는 편입니다. 다른 사람에게 편안한 느낌을 주고 착한 성격 덕분에 주위에는 항상 친구들로 가득합니다. 이토록 사랑스러운 소년을 만나면 어떻게 좋아하지 않을 수 있을까요?'},
 21693: {'zh-CN': '或许你的外表会给人一种难以靠近的距离。你虽然有些高冷，让别人总是觉得你难以接近，但其实你的内心热情似火，十分奔放。喜欢把所有事情都自己一个人扛着，从不表露自己的内心世界，于是你就扮演着各种冷酷来掩饰，来增加彼此的距离。你是一个难以捉摸的人，因此你总是让别人想去靠近你、了解你、保护你。你看似高冷，想跟任何人保持距离感。但恰恰相反，你散发的这种魅力反而吸引了一大批的小迷妹和小迷弟。',
  'ko': '당신의 차가움 때문에 다른 사람들이 쉽게 다가가지 못하지만 사실 당신의 마음은 열정으로 넘칩니다. 모든 것을 혼자 해결하려고 하고 자신의 내면을 절대 드러내지 않기 때문에 차가운 이미지로 타인과 거리를 둡니다. 당신은 종잡을 수 없는 사람이기에 다른 사람들이 당신에게 다가가고 싶어 하지만 당신은 항상 거리감을 유지하고 싶어 합니다. 그러나 정반대로 당신이 풍기는 이런 매력은 오히려 상대의 마음을 움직입니다.'},
 56075: {'zh-CN': '中秋宴俗. 明代宫廷时兴吃螃蟹。螃蟹用蒲包蒸熟后，众人围坐品尝，佐以酒醋。食毕饮苏叶汤，并用之洗手。宴桌区周，摆满鲜花、大石榴以及其他时鲜，演出中秋的神话戏曲。清宫多在某一院内向东放一架屏风，屏风两侧搁置鸡冠花、毛豆技、芋头、花生、萝卜、鲜藕。屏风前设一张八仙桌，上置一个特大的月饼，四周缀满糕点和瓜果。祭月完毕，按皇家人口将月饼切作若干块，每人象征性地尝一口，名曰“吃团圆饼”',
  'ko': '추석연회. 명대 궁중에서는 게가 유행했다. 게를 부들포에 싸서 삶은 후 여럿이 모여 즐겼다. 식사가 끝나면 소엽탕을 마셨으며, 그것으로 손도 씻었다. 연회 식탁은 생화, 석류, 기타 신선한 과일로 장식하였고, 신화를 주제로 한 연극을 감상하였다. 청대 궁중에서는 정원의 동쪽에 병풍을 설치하고 양쪽에 맨드라미, 풋콩 가지, 토란, 땅콩, 무우, 연근을 두었다. 병풍 앞쪽에는 팔선탁자를 설치하고, 그 위에 커다란 월병을 놓았고, 그 주변에 떡과 과일을 놓았다. 제사가 끝나면 황실 사람 수에 맞게 월병을 잘라서 모두가 한입씩 먹었는데, 이를 “단원병 먹기”라고 했다.'},
 32894: {'zh-CN': '★ 装备此神兵并变身后，施放武功时有10%几率使周围3个敌人进入混沌状态，持续5秒（满星25%几率，混沌效果不可驱散）. ★ 混沌状态下的敌人在施放武功时有30%几率使敌人自身与其周围6米内的友方受到2秒的恐惧效果（添加时无视控制抗性）. ★ 友方包括：自己的宠物、队友、武道会/帮战/城战/会武/势力战中的同阵营成员。注意：野外地图中在帮派模式下，不包括同帮派成员只包括队友',
  'ko': '★ 신병 착용 및 변신 후 무공 시전 시 10% 확률로 주위 목표 3명에게 혼돈 상태 발동, 5초간 지속(최고 성급 달성 시 25%, 혼돈 상태 제거 불가). ★ 혼돈 상태 목표가 무공 시전 시 30% 확률로 목표 자신과 목표 주위 6m 아군에게 2초간 공포 효과 발동(추가할 때 제어저항 무시). ★ 아군은 자신의 펫, 파티원, 비무대회/문파전/공성전/대전/세력전 포함. 주의: 필드맵 문파 모드에서 동일 문파원이 포함되지 않고 파티원만 포함'},
 56076: {'zh-CN': '月光马儿. 由早期纯道教色彩的以嫦娥为主的月宫图景演变为佛道交融的月光菩萨与捣药玉兔并在的世俗形象。这个时期，人们供奉绘有月光菩萨的月光纸，也叫“月光马儿”。富察敦崇的《燕京岁时记》记载：“月光马者，以纸为之，上绘太阴星君，如菩萨像，下绘月宫及捣药之兔。人立而执杵，藻彩精致，金碧辉煌，市肆间多卖之者。长者七、八尺，短者二、三尺，顶有二旗，作红绿，笆或黄色，向月而供之”',
  'ko': '월광마. 초기에는 도교적 색채가 짙은 항아를 위주로 한 월궁 풍경에서 불교와 합쳐진 월광보살과 옥토끼가 합쳐진 세속적 이미지로 바뀌었다. 이때, 사람들 손에 월광보살 모양의 종이를 들고 있었는데, 이것이 “월광마”이다. 부찰돈숭의 <연경세시기>에서 “종이신상은 종이로 만들었고 위쪽에는 태음성군이 그려져 있어서 보살상과 같다고 하였고, 아래쪽에는 월궁과 옥토끼가 그려져 있다. 무늬와 색채가 화려하고 휘황찬란하여 상점에서 많이 팔렸다. 긴 것은 7, 8척, 짧은 것은 2, 3척의 길이였으며, 꼭대기에 깃발이 두 개가 있어 홍록, 황색으로 달을 향해 그것을 바쳤다.”라고 했다.'},
 31092: {'zh-CN': '{_x005f_x0001_}，赛季开始，此时可组建战队. {_x005f_x0001_}，可以通过匹配跨服参加海选赛. {_x005f_x0001_}，取跨服海选赛积分前64名，进入锦标赛，并随机对手. 如果参赛队伍大于等于128个，则取参赛队伍的前128名，分为【武皇组】和【武帝组】两个分组，并随机分配队伍（注：分组时队伍完全随机，两组之间不存在高下之分）',
  'ko': '{_x005f_x0001_} 비무대회 시작, 팀 창설 가능. {_x005f_x0001_} 전 서버 예선전 진행. {_x005f_x0001_} 예선 점수 랭킹 64위까지 토너먼트 진출'},
 54272: {'zh-CN': '古人将大暑分为三候. 一候腐草为萤：大暑时，萤火虫卵化而出。古人认为，萤火虫乃腐草所变，萤火虫又名烛宵、耀夜，是大暑迎接立秋的诗意之虫，轻罗小扇扑流萤，萤火虫在静夜里穿梭时，其实凉爽的秋已经不远了。. 二候土润溽暑：天气开始闷热，土地也很潮湿。溽是湿，大暑时，湿气浓重，湿热令人难耐。. 三候大雨时行：大暑时节，因湿气积聚而时常大雨滂沱，经常有大的雷雨。',
  'ko': '옛사람은 대서를 삼후로 나누었다.. 초후에 풀이 썩어서 반딧불이 된다. 대서에 반딧불이의 알이 부화한다. 옛사람은 반딧불이가 풀이 썩어서 변하는 것으로 여겼다. 그래서 반딧불이를 촉소, 요야로 불렀다. 반딧불이는 ‘가벼운 비단부채로 반딧불이를 쫓네’라는 대서에 입추를 맞이하는 시에도 등장한다. 반딧불이가 조용한 밤하늘을 날아다니면 시원한 가을이 멀지 않았다는 뜻이기로 하다.. 차후에 흙에 습기가 많고 무덥다: 날씨가 무더워지기 시작하고 토지도 습해진다. 젖다는 습하다는 의미로 대서에 습기가 강해지고 습한 무더움이 사람을 견디기 힘들게 만든다.. 말후는 큰 비가 때때로 내린다: 대서에 습기가 모이면서 종종 큰 비가 내리고 강한 뇌우가 내린다.'},
 53965: {'zh-CN': '★ 当变身后，激活【往生】效果. ★ 往生效果：10秒内施放伤害类武功时，根据此武功造成的总伤害，将对自己和周围10米内全部友方恢复[总伤害*100%]点气血. ★ 每次恢复气血时，有15%几率将往生效果复制给任意一个玩家，使其获得5秒的往生效果（无法再次传递）. ★ 若复制给自己，则延长往生效果的时长（最多3次）. ★ 此神兵满星后，复制几率为60%',
  'ko': '★ 변신 후 의 생명 회복. ★ 매회 생명 회복 시 15% 확률로 왕생 효과를 임의의 유저에게 복사, 5초간 왕생 효과 획득(재전파 불가). ★ 자신이 복사하면 왕생 시간이 연장됨(최대 3회). ★ 최고 성급 달성 시 복사 확률 60%'},
 54276: {'zh-CN': '送大暑船. 送大暑船活动在浙江台州沿海已有几百年的历史。大暑船完全按照旧时的三桅帆船缩小比例后建造，船内载各种祭品。活动开始后，多名渔民轮流抬着大暑船在街道上行进，鼓号喧天，鞭炮齐鸣，街道两旁站满祈福人群。“大暑船”最终被运送至码头，进行一系列祈福仪式。随后，这艘“大暑船”被渔船拉出渔港，然后在大海上点燃，任其沉浮，以此祝福人们五谷丰登，生活安康。。',
  'ko': '대서선 띄우기. 대서선 띄우기는 절강 태주 연해에서 수백년의 역사를 지니고 있다. 대서선은 옛 범선을 축소하여 만든 것으로 배 안에 각종 제물이 담겨있다. 의식을 시작하면 어민들이 교대로 대서선을 들고 거리를 행진한다. 북소리와 폭죽 터지는 소리가 요란하고 거리 양쪽으로 복을 기원하는 사람으로 가득하다. ‘대서선’이 부두에 도착하면 복을 기원하는 의식이 진행된다. 그리고 배는 어선에 이끌려 바다로 나가 불에 태워진다. 배가 침몰할 때 사람들은 풍년과 평안함을 기원한다.'},
 21687: {'zh-CN': '刀子嘴豆腐心。嘴上说着不可以不愿意，但心却软的像一个棉花糖，只要对你多说几句话，你立马就会心软，这可能是别人对你最多的评价。你从不故意表现，都是下意识的温暖;你可能对自己粗心大意，对别人却细心如尘;人除了有点暖还有点萌,付出不会想着索取回报。你就像个小太阳一样，不停的发热又发光。虽然你前期可能有些慢热，可一旦“焐热了”，暖起来可是连你自己都害怕!',
  'ko': '말은 날카롭게 하지만 마음은 부드럽습니다. 말로는 싫다고 하지만 마음은 누구보다도 달콤한 사람입니다. 다른 사람들이 당신에 대한 평가는 몇 마디만 하면 금방 마음이 약해진다는 것입니다. 당신은 절대 의도적으로 표현하지 않고 모두 진심으로 표현합니다. 타인을 항상 조심스럽게 대하고 베푼 것을 돌려받으려고 애쓰지 않습니다. 당신은 작은 태양처럼 끊임없이 빛을 발합니다. 비록 느리지만 일단 따뜻해지면 자신도 무서울 정도입니다.'},
 25861: {'zh-CN': '对周围8米内敌人造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，必然命中。. 攻击姿态下使自身在5秒内，根据周围敌方玩家与宠物的数量提升攻击属性，基础提高5%，每个敌方增加3%，最高20%；. 防御姿态下使自身在5秒内，根据周围友方玩家与宠物的数量提升防御属性，基础提高5%，每个友方增加3%，最高20%。',
  'ko': '주변 8m내의 적에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 주고, 반드시 명중.. 공격자세에서는 5초간, 주변 적군 유저와 펫 수량에 따라 자신의 공격 속성 기본이 5% 증가하며, 적군 수마다 3% 증가하여, 최대 20%까지 증가. 방어자세에서는 5초간, 주변 아군 유저와 펫 수량에 따라 자신의 방어 속성 기본이 5% 증가하며, 아군 수마다 3%증가해, 최대 20%까지 증가'},
 25859: {'zh-CN': '对周围8米内敌人造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，必然命中。. 攻击姿态下使自身在5秒内，根据周围敌方玩家与宠物的数量提升攻击属性，基础提高5%，每个敌方增加3%，最高20%；. 防御姿态下使自身在5秒内，根据周围友方玩家与宠物的数量提升防御属性，基础提高5%，每个友方增加3%，最高20%。',
  'ko': '주변 8m내의 적에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 주고, 반드시 명중.. 공격자세에서는 5초간, 주변 적군 유저와 펫 수량에 따라 자신의 공격 속성 기본이 5% 증가하며, 적군 수마다 3% 증가하여, 최대 20%까지 증가. 방어자세에서는 5초간, 주변 아군 유저와 펫 수량에 따라 자신의 방어 속성 기본이 5% 증가하며, 아군 수마다 3% 증가하여, 최대 20%까지 증가'},
 21689: {'zh-CN': '你的性格很单纯，在你的世界里非黑即白，你希望世界能够简简单单的没有伤害，你的心愿就是世界和平，你就像孩子般的天真无邪，就算被欺骗还是选择宁愿相信世界会有他的光明，这样的你很容易勾起人们的保护欲，虽然你有时候会很大气不过这也掩饰不了你有一颗小正太的心。不过，能够像一个小正太一样的活着，保持自己的天真纯洁，何尝不是一件很值得炫耀的事情呢！！',
  'ko': '당신의 성격은 매우 단순합니다. 세상 모든 것이 단순하고 무해하기를 원하고 소원은 세계 평화입니다. 당신은 아이처럼 순진하여 타인에게 상처를 받아도 세상에는 또다시 빛이 찾아온다고 믿습니다. 그래서 쉽게 사람들의 보호를 불러일으킬 수 있습니다. 이토록 밝고 순진하게 산다는 것이 얼마나 자랑스러운 일일까요?'},
 21695: {'zh-CN': '你是一个特别爱奇思妙想的人。你懂得创新，喜欢探索一切新鲜有趣的东西，你同时也对世界充满了求知欲，所以脑子里也会有很多好玩的鬼点子。虽然有时候你会给别人一种玩世不恭的感觉，但其实这都是假象！！你就像一个小精灵一样，能够给别人带来许多欢乐和浪漫，你开朗且热情。让别人感觉你就是一个有内涵的“花瓶”。跟这样的你相处久了，只会让别人越来越喜欢你。',
  'ko': '당신은 기발한 것을 좋아하는 사람입니다. 혁신적이고 새롭고 흥미로운 것을 탐구하고 세상에 대한 지식으로 가득하기 때문에 머릿속에 재미난 아이디어도 많습니다. 당신은 작은 요정처럼 많은 기쁨과 낭만을 주고 항상 밝고 열정적입니다. 당신의 마음속에 꽃병이 있어 시간이 지날수록 점점 더 당신을 좋아하게 될 뿐입니다.'},
 21700: {'zh-CN': '温柔是你的代名词，你对周围的人都保持着一颗柔和的心。和你相处会让人感到十分惬意舒适，思维缜密的你也可以帮助朋友解决很多难题。不谙世事的你拘谨害羞，表现温顺，让人看了就有很强的保护欲！一旦有人像一个邻家大哥哥一样保护你，呵护你的时候，你就会像只温柔的小兔纸一样，黏住对方，生怕你的大哥哥离开一样，真是温柔又让人忍不住去疼爱你的小宝贝啊！',
  'ko': '상냥함은 당신의 대명사이고 주변 사람들에게 부드러운 마음을 가지고 있습니다. 당신과 함께 있으면 매우 편안하고 똑똑한 당신은 친구들의 많은 난제를 해결하는 데 도움을 줍니다. 당신은 수줍음이 많고 온순해 보여서 누군가의 보호를 받으면 한 마리의 토끼처럼 온순하고 잘 따릅니다. 상대가 사랑하지 않을 수 없는 사람입니다.'},
 54277: {'zh-CN': '饮食. 夏季的饮食调养是以暑天的气候特点为基础，由于夏令气候炎热，易伤津耗气，因此常可选用药粥滋补身体。《黄帝内经》有“药以去之，食以随之”，“谷肉果菜，食养尽之”的论点。这个时节，肠胃的消化功能较为薄弱，饮食以清淡为主，不可多吃肥腻、辛辣、煎炸食物。除了多喝水、常食粥、多吃新鲜果蔬外，还可适当多食用些清热、健脾、利湿、益气等食物。',
  'ko': '음식. 여름 음식은 더운 기후의 특징을 토대로 하며, 여름 날씨는 무더워 쉽게 기운이 빠기 때문에 약죽으로 몸을 보양한다. 《황제내경》에 “약으로 그것을 제거하고 음식으로 그것을 따른다”, “곡물, 고기, 과일, 채소 등 음식으로 정양하면 모두가 낫는다”라는 말이 있다. 이런 계절에는 위장의 소화 기능이 약해지기 때문에 담백한 음식 위주로 먹어야 하며, 기름지고 맵고 튀긴 음식은 줄여야 한다. 물을 많이 마시고, 죽을 자주 먹고, 과일과 채소를 많이 먹는 것 외에도 열을 내리고, 비장을 건강하게 하고, 습한 것을 없애고, 기운을 북돋는 음식을 많이 먹어야 한다.'},
 56072: {'zh-CN': '吴刚伐桂. 传说吴刚是天庭中的一位粗鲁的天将，被嫦娥的美丽深深吸引。也不顾对方的拒绝，一次又一次地跑到月宫纠缠。嫦娥不堪其扰，于是指向月中桂树说，它枝条太长了，今夜你若能将它砍断，便答应你的追求。吴刚心花怒放，心想这算什么难题，抡起斧头就砍。可每次拔出斧头，桂树的树身便恢复如初。于是他一斧又一斧地砍，桂树总是不断。一至砍到今天。',
  'ko': '계수베기. 천계의 장수였던 오강은 항아의 미모에 깊게 빠졌다. 상대가 거절해도 계속해서 월궁에 찾아갔다. 더는 참지 못한 항아가 계수나무를 가리키며 ‘나무 가지가 너무 긴데 오늘밤 베어버린다면 당신의 요구를 받아들이겠다’고 말했다. 오강은 기뻐하며 속으로 그게 뭐가 어렵냐 생각하며 도끼로 나무를 베었다. 허나 매번 도끼질을 할 때마다 계수나무가 다시 회복됐다. 계속해서 도끼질을 했지만, 나무는 잘리지 않았다. 그래서 오늘날까지 자르고 있다고 한다.'},
 56071: {'zh-CN': '民间拜月. 夕月，即祭拜月神。设大香案，摆上月饼、西瓜、苹果、红枣、李子、葡萄等祭品，其中月饼和西瓜是绝对不能少的。西瓜还要切成莲花状。在月下，将月亮神像放在月亮的那个方向，红烛高燃，全家人依次拜祭月亮，然后由当家主妇切开团圆月饼。切的人预先算好全家共有多少人，在家的，在外地的，都要算在一起，不能切多也不能切少，大小要一样。',
  'ko': '달에게 절하기. 저녁달, 즉 달의 신에게 제사를 지낸다. 상을 차리고 월병, 수박, 사과, 대추, 자두, 포도 등의 음식을 올린다. 그 중에 월병과 수박은 절대 빠져선 안 된다. 수박은 연꽃 모양으로 썰어야 한다. 달의 신상을 달빛 비치는 방향에 놓고 촛불을 밝히고 온가족이 차례대로 달에 제사를 드린다. 그리고 주부가 월병을 자른다. 자르는 사람은 가족이 그 자리에 있든 없든 가족수에 맞게 똑같은 크기로 자른다.'},
 50802: {'zh-CN': '럭키상자. 융령단 1~3개, 축복석 1~3개, 황화 씨앗 4개, 성화 씨앗 1~3개, 황남정화 1~3개, 북제칙령 1~3개, 자색 부적상자 2~6개, 백련결정 2~6개, 흑첩원석 2~6개, 정금석 1~2개, 복희하도계 2~4개, 신수내단 1~3개, 현문비문 1~3개를 랜덤으로 획득합니다.',
  'ko': '럭키상자. 융령단 1~3, 축복석 1~3, 황화 씨앗 4, 성화 씨앗 1~3, 황남정화 1~3, 북제칙령 1~3, 자색 부적상자 2~6, 백련결정 2~6, 흑첩원석 2~6, 정금석 1~2, 복희하도계 2~4, 신수내단 1~3, 현문비문 1~3을 랜덤으로 획득합니다.'},
 56073: {'zh-CN': '月饼传说. 元朝末年，汉人打算团结起来反抗蒙古人的统治，却苦于无从传递消息。后来刘伯温想出一条计策，到处散布流言，说有冬瘟流行，除非家家户户都在中秋节买月饼来吃，才能避免。人们买了月饼回到家中，发觉里面藏着纸条，上面写着：“中秋夜，杀鞑子，迎义军！” 于是众人纷纷起义反抗统治者，中秋节吃月饼的习俗就是这样留下来的。',
  'ko': '월병전설. 원나라 말, 한인이 힘을 모아 몽골인의 통치에 저항하려 하였으나, 이 소식을 전파할 방법이 없었다. 나중에 유백온이 계책 하나를 생각해냈다. 사방에 겨울 역병이 도는데 추석에 월병을 사서 먹으면 화를 피할 수 있다고 했다. 사람들이 월병을 사서 집으로 돌아가는데 안에 숨겨진 쪽지를 발견한다. 쪽지에는 ‘추석날 밤에 오랑캐를 물리치고 의용군을 맞이하자!’라고 써 있었다. 그래서 사람들이 일어나 몽골에 저항하였다. 추석에 월병을 먹는 습관은 이때부터 전해져 내려왔다.'},
 2041: {'zh-CN': '累计充值10000元宝即可享受该级特权. 包含贵族9等级所有特权. 享受每日体力福利活动过期补领特权（邮件发放）. 可使用跨服频道. 每日可开启青铜/白银宝箱数量翻倍（20个）. 每日可购买体力次数翻倍（16次）. 每日可购买参悟次数翻倍（10次）. 每日可发1000元宝的帮派红包. 生产和分解物品消耗时间再次降低',
  'ko': '25000금화 누적 충전 시 아래 특권 사용 가능. . VIP9 특권 사용. 매일 체력 보상 수령 시간이 지나도 서신으로 발송. 서버채널에서 채팅 가능. 청동/백은 보물상자 사용 횟수 2배 적용(20회). 체력 구매 횟수 2배 적용(16회). 각성 횟수 4회 구매 가능. 문파 금일봉 최대 1000 금화 발송 가능.'},
 8442: {'zh-CN': '传说来自遥远的彼方之岛——夜萝洲的神秘组织，头领自称‘魔王’。. 整个组织由羽鸦魔大王所统领，不知什么原因，藏匿于神武门中不轻易离开。. 随着夜萝洲的出现，他们的来历似乎也明了起来。羽鸦魔似乎是在‘三魔王动乱’的斗争中败下阵来的输家，在中原地区蛰伏，期望能够重回夜萝洲。. 该组织不介入任何武林争端，属于中立势力。',
  'ko': '전설 속에 등장하는 머나먼 섬인 야라주의 신비로운 조직에서 왔다고 합니다. 자신을 [마왕]이라고 칭하는 자를 두목으로 섬기고 있습니다. . 조직은 우아마 대왕이 이끌고 있으나 무슨 이유에서 인지 신무문에서 떠나지 않고 있습니다. . 야라주가 나타나게 되면서 이들의 근원이 밝혀지기 시작했습니다. 우아마는 [삼마왕 대결]에서 패배하면서 중원 지역에 숨어 지내고 있었지만 이제 다시 야라주로 돌아가고자 합니다.. 이 조직은 무림의 모든 일에 간섭하지 않으며 중립 세력에 속해 있습니다.'},
 25824: {'zh-CN': '对扇形目标造成2次伤害，每次[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，并使周围敌人沉默3秒，根据武功起手时周围友方玩家与宠物的数量提升伤害，每个单位提升20%，最高提升100%。. 攻击姿态下额外使目标5秒内躲闪降低20%；. 防御姿态下额外使自身5秒内躲闪提高20%。',
  'ko': '부채꼴 범위의 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 2회 주고, 주변 적을 3초간 침묵시킴, 무공 시전 시, 주변 아군 유저와 펫의 수량에 따라, 단위당 피해 20%가 증가하며, 최대 100%까지 증가. 공격자세에서는 목표의 회피를 5초간 20%를 감소시키고. 방어자세에서는 5초간 자신의 회피가 20% 증가'},
 25832: {'zh-CN': '对扇形目标造成2次伤害，每次[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，并使周围敌人沉默3秒，根据武功起手时周围友方玩家与宠物的数量提升伤害，每个单位提升20%，最高提升100%。. 攻击姿态下额外使目标5秒内躲闪降低20%；. 防御姿态下额外使自身5秒内躲闪提高20%。',
  'ko': '부채꼴 범위의 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 2회 주고, 주변 적을 3초간 침묵시킴. 무공 시전 시, 주변 아군 유저와 펫의 수량에 따라, 단위당 피해 20% 증가하며, 최대 100%까지 증가. 공격자세에서는 목표의 회피를 5초간 20% 감소시키고. 방어자세에서는 5초간 자신의 회피가 20% 증가'},
 25847: {'zh-CN': '向前冲锋并击退目标，对目标造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，并使目标眩晕2秒，根据武功起手时周围友方和敌方玩家与宠物的数量提升伤害，每个单位提升30%，最高提升150%。. 攻击姿态下使自己3秒内伤害提升300%；. 防御姿态下使自己在4秒内忽视所有伤害。',
  'ko': '전방으로 돌격하여 목표를 격퇴하고, 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 주고, 목표를 2초간 기절시킴. 무공 시전 시, 주변 아군 유저와 펫의 수량에 따라 단위당 30% 피해가 증가하며 최대 150%까지 상승. 공격자세에서는 3초간 자신의 피해가 300% 증가. 방어자세에서는 4초간 모든 피해를 무시'},
 25855: {'zh-CN': '向前冲锋并击退目标，对目标造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，并使目标眩晕2秒，根据武功起手时周围友方和敌方玩家与宠物的数量提升伤害，每个单位提升30%，最高提升150%。. 攻击姿态下使自己3秒内伤害提升300%；. 防御姿态下使自己在4秒内忽视所有伤害。',
  'ko': '전방으로 돌격하여 목표를 격퇴하고, 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 주고, 목표를 2초간 기절시킴. 무공 시전 시, 주변 아군 유저와 펫의 수량에 따라 단위당 30% 피해가 증가하며 최대 150%까지 상승. 공격자세에서는 3초간 자신의 피해가 300%증가. 방어자세에서는 4초간 모든 피해를 무시'},
 21704: {'zh-CN': '你在爱情中都是比较成熟的一方。你成熟、理性、优雅，有着超于年龄的想法，所以在爱情中往往都占据着主导的角色，受不了被驾驭。但你对亲朋好友却照顾有加，对朋友也会两肋插刀，不管你在哪里都会凭借你自身独特的气质都能够艳压群芳，成为众人眼中的焦点。“你赢我陪你君临天下，你输我陪你东山再起”用这句话来形容你在合适不过了！',
  'ko': '당신은 사랑에 있어서 성숙한 편입니다. 게다가 이성적이고 우아하며 깊은 생각을 가지고 있기 때문에 사랑에 있어서는 항상 주도적인 역할을 합니다. 하지만 당신은 친한 친구를 항상 배려하고 의리를 지킵니다. 당신이 어디에 있든 자신의 독특한 기질로 군중을 흔들 수 있고 모든 사람들의 관심을 받을 수 있습니다.'},
 21685: {'zh-CN': '你的感情总是开始得小心翼翼，生怕因为自己的鲁莽而错失了自己深爱的人。在彼此相爱之后，你往往也是痴情和专注的，并且会为了爱情付出所有深情。你超懂浪漫，经常会有一些甜言蜜语。你希望能带着自己爱的人，看遍世间每处风景，留下你们爱的脚印。面对你爱的人，你的字典里没有“变心”二字，愿把一根肋骨为剑，护她一生不受伤害。',
  'ko': '당신은 자신의 무모함 때문에 사랑하는 사람을 잃을까 봐 항상 조심스럽게 행동합니다. 사랑이 시작된 후에도 한 사람에게만 집중하고 사랑을 위해 모든 것을 바치게 됩니다. 로맨틱한 당신은 달콤한 말을 많이 하는 편입니다. 사랑하는 사람을 데리고 세상의 모든 풍경을 보는 것을 원합니다. 사랑하는 사람에게는 절대 마음이 변하지 않고 상대가 상처받지 않게 늘 지켜줍니다.'},
 21697: {'zh-CN': '如何击垮骄傲坚定的你？“只要让你谈一场恋爱就好了”！你不会轻易去爱，但一旦爱必定刻骨铭心，哪怕前路充满荆棘，哪怕遍体鳞伤你也很难放下心中的爱。爱就像你内心里小心呵护的宝贝，很珍贵，也过于珍贵。当你真正爱上一个人的时候，你的整个世界只有对方，哪怕你与全世界为敌。被你爱是幸福的，但不是每个人都能懂你的爱…',
  'ko': '당신은 쉽게 사랑할 수는 없지만 한 번 사랑하면 상처투성이가 되어도 사랑을 놓지 못할 것입니다. 사랑은 당신의 내면에 있는 소심한 아이처럼 너무 소중합니다. 당신이 누군가를 진정으로 사랑하게 되면 당신의 세계는 상대로 가득하게 됩니다. 당신의 사랑을 받는 것은 행복하지만 모든 사람이 당신의 사랑을 이해할 수 있는 것은 아닙니다…'},
 32898: {'zh-CN': '★ 装备此神兵并变身后，界面中出现兵主按钮，点击使周围处于神兵变身状态的敌人减少其10秒变身时间，冷却时间3分钟（满星90秒）。. ★ 装备此神兵并变身后，命中、躲闪、暴击、韧性提升5%（满星10%），持续8秒。. 注意：每个人神兵变身期间只能受到一次兵主效果；被降低变身时间后，最少保留5秒变身时间。',
  'ko': '★ 신병 변신 후 병주 버튼 터치 시 주위 신병 변신 상태 목표의 변신 시간 10초 감소, 쿨타임 3분(최고 성급 달성 시 90초). ★ 신병 변신 후 명중, 회피, 치명타, 인내력 5% 증가(최고 성급 달성 시 10%), 8초간 지속. 주의: 신병마다 변신 기간 동안 병주 효과 1회만 받고, 변신 시간이 감소된 후 최소 5초간 변신 시간이 유지됩니다.'},
 2045: {'zh-CN': '累计充值80000元宝即可享受该级特权. 综合和帮派频道发言特殊效果. 开启竞技场防守阵容隐藏功能. 包含贵族13等级所有特权. 补做试炼活动次数上限翻倍（6次）. 购买金币次数上限翻倍（120次）. 竞技场购买次数再翻倍（48次）. 每日可购买神木鼎炼化次数20次. 每日可发4000元宝的帮派红包.',
  'ko': '200000금화 누적 충전 시 아래 특권 사용 가능. . VIP13 특권 사용. 종합 및 문파채널에서 채팅 시 특수효과. 전장에서 방어 진형 숨기기 기능 사용 가능. 활약보충 횟수 2배 적용(최대 6회). 금전 구매 횟수 2배 적용(120회). 전장 도전 횟수 총 48회 구매 가능. 신목정 연화 횟수 20회 구매 가능. 문파 금일봉 최대 4000 금화 발송 가능.'},
 21698: {'zh-CN': '你喜欢挑战各种新奇的事物，不喜欢被约束着，喜欢自由。所以你会和各种各样的人打交道，而浑身上下散发着可爱气息的你，很容易就可以萌到大家，成为大家心中的宝贝，得到大家的认可和呵护。在你身边的人，会情不自禁陷入你的可爱中无法自拔，看到萌萌的你，会一天都元气满满！毕竟谁都喜欢自己身边有一个萌萌哒的可爱妹纸啊。',
  'ko': '당신은 각종 신기한 것에 도전하는 것을 좋아하고 구속받는 것을 좋아하지 않습니다. 그래서 당신은 다양한 사람들을 상대하는 것을 좋아합니다. 사랑스러움으로 가득한 당신은 쉽게 귀여움을 받습니다. 당신 곁에 있는 사람은 나도 모르게 당신의 귀여움에 빠져 헤어나지 못하고 귀여운 당신을 바라보면 하루 종일 기쁨으로 가득합니다.'},
 8438: {'zh-CN': '北海冰宫谭雨轩之女，脾气娇蛮任性，到处惹是生非，让谭雨轩颇为头疼。. 从爸爸身边逃离之后，芙蓉感觉到了自由，但也感觉到在江湖的不易。不过她转瞬之间就把烦恼扔在一边，尽情享受没有人管束的日子。. 人长得漂亮，脾气虽然有些暴躁，但会适时的表现出小鸟依人的样子，所以深受江湖中年轻侠士的喜欢，追求者不少。',
  'ko': '북해궁주의 딸 부용은 교만한 성격에 말썽꾸러기입니다.. 아버지의 울타리를 벗어난 부용은 자유를 느꼈지만 강호에서의 어려움도 터득하였습니다. 그러나 그녀는 아랑곳하지 않고 마음껏 자유를 누렸습니다.. 사람은 예쁘고 조금 거칠지만 때론 사랑스럽고 귀여운 모습을 보여 주기 때문에 강호의 젊은 협객들에게 인기가 아주 높습니다.'},
 25930: {'zh-CN': '★射程：3.5米  冷却：40秒. 施展时若距离目标6米以内，则快速闪烁到目标面前，对面前扇形内3个敌人造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]伤害，并有{_x005f_x0001_}%几率使目标致盲5秒，致盲期间造成伤害时有50%几率只造成极少伤害',
  'ko': '★사거리: 3.5m  쿨타임: 40초. 시전 시 목표와의 거리가 6m 미만이면 빠르게 다가가 전방 부채꼴 범위의 3개 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 입히고 {_x005f_x0001_}% 확률로 목표 실명 5초, 실명 상태에서 피해를 입힐 때 50% 확률로 아주 적은 피해를 입힘'},
 25920: {'zh-CN': '★射程：10米  冷却：40秒. 对前方圆形内最多5个目标造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]伤害并有{_x005f_x0001_}%几率为其附加震撼状态，持续7秒，期间大幅减速且命中降低20%，添加时无视持续抗性,添加后不可驱散/叠加/延长',
  'ko': '★사거리: 10m  쿨타임: 40초. 전방 원형 범위의 최대 5개 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 입히고 {_x005f_x0001_}% 확률로 목표 진감, 7초간 지속, 기간 동안 대폭 감속 및 명중 20% 감소, 추가할 때 지속저항 무시, 추가 후 제거/중첩/연장 불가'},
 25916: {'zh-CN': '★射程：10米  冷却：45秒. 对单体目标造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]伤害并有{_x005f_x0001_}%几率为其附加千蛛万毒状态，持续10秒，期间每秒损失3%气血、躲闪降低20%，添加时无视持续抗性,添加后不可驱散/叠加/延长',
  'ko': '★사거리: 10m  쿨타임: 45초. 단일 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 입히고 {_x005f_x0001_}% 확률로 목표에게 천주만독 상태 추가, 10초 지속, 기간 동안 1초마다 3% 생명 감소, 20% 회피 감소, 추가할 때 지속저항 무시, 추가 후 제거/중첩/연장 불가'},
 50841: {'zh-CN': '럭키상자. 스페셜 중급 선택상자*20~30, 스페셜 고급 선택상자*10~30, 스페셜 최고급 선택상자*1~3, 100레벨 특급 럭키상자*1~3, 고급 내갑 조각 럭키상자*1~3, 북제칙령 럭키상자*1~3, 흑첩원석 럭키상자*1~3개를 랜덤으로 획득합니다.',
  'ko': '럭키상자. 스페셜 중급 선택상자*20~30, 스페셜 고급 선택상자*10~30, 스페셜 최고급 선택상자*1~3, 100레벨 특급 럭키상자*1~3, 고급 내갑 조각 럭키상자*1~3, 북제칙령 럭키상자*1~3, 흑첩원석 럭키상자*1~3개를 랜덤으로 획득합니다.'},
 20933: {'zh-CN': '神地运输官：所谓上等人选，就是那些自认为所作所为是正确的人。价值观是最不容易被矫正的东西，这些人因为生活的关系天生就对村子不满，咱们只需要稍微引导一下就行；中等人选，就是那些知道自己做的不对，但拿了好处之后，也能当成对的人。说白了，不是蠢、就是坏，想在骚动中捞一笔，就靠这个吃饭……',
  'ko': '신지운수관. 소위 상류층은 자기가 생각하고 행동하는 게 모두 옳다고 여기죠. 그렇기에 가치관을 바로잡기가 쉽지 않아요. 이러한 사람들은 선천적으로 마을에 불만을 느끼고 있기 때문에, 우리가 약간만 가르쳐 주면 돼요. 그리고 중산층은 자신의 잘못을 알고 있어요, 하지만 좋은 걸 손에 넣게 되면 태도가 바뀐답니다. 간단히 말해서, 바보도 아니고 나쁘지도 않지만, 혼란을 틈타서 한 몫 챙기려는 자들이죠……'},
 50832: {'zh-CN': '럭키상자. 융령단*1, 오절비록*1, 세련석*10, 오독주*10, 태공육도*1, 세수단*5, 양구기담*3, 천외운석*2, 중급 신병 경험석*5, 중급 펫 경험단*20, 고급 기마술 요결*3~6, 천년동정*2, 양금마편*1~2개를 랜덤으로 획득합니다.',
  'ko': '럭키상자. 융령단*1, 오절비록*1, 세련석*10, 오독주*10, 태공육도*1, 세수단*5, 양구기담*3, 천외운석*2, 중급 신병 경험석*5, 중급 펫 경험단*20, 고급 기마술 요결*3~6, 천년동정*2, 양금마편*1~2개를 랜덤으로 획득합니다.'},
 53673: {'zh-CN': '礼包. 打开可选择地魔之眼碎片×30，彼岸花碎片×30，霸王鬼面甲碎片×30，伏魔花灵剑碎片×30，巫蛊刺碎片×30，寒玉神杖碎片×30，噬月狼屠碎片×30，神弓之魂×10，火麟天羽碎片×30，鬼鸣剑碎片×30，六道降魔杵碎片×30，羽华凌云刃碎片×30, 万能神兵碎片×50。',
  'ko': '패키지. 오픈 후 지마의 눈 조각×30, 피안화 조각×30, 패왕귀면갑 조각×30, 복마화령검 조각×30, 무고척 조각×30, 한옥신장 조각×30, 서월낭도 조각×30, 신궁 영혼×10, >화린천우 조각×30, 괴명검 조각×30,  육도강마저 조각×30, 우화능운인 조각×30, 만능 신병 조각×50 중에서 선택할 수 있습니다.'},
 32913: {'zh-CN': '★ 装备此神兵并变身后，召唤一个自身的幻象，继承自身80%属性（满星继承100%属性），幻象施放武功时随机附加嘲讽、眩晕、定身其中的一种状态，持续2秒. ★ 幻象死亡时，为周围所有友方恢复[最大气血*40%]点气血（满星80%），并且使友方5秒内受伤害降低30%（满星60%）',
  'ko': '★ 신병 착용 및 변신 후 무공 시전 시 자신의 분신을 소환하고 캐릭터 속성의 80%가 적용됩니다(최고 성급일 땐 100% 적용). 분신이 무공 시전 시 임의로 도발, 기절, 이동불가 중 1개 효과가 적용되고 2초간 지속됩니다.. ★ 분신이 사망하면 주변 아군의 [최대 생명*40%] 만큼 치유합니다(최고 성급일 땐 80%적용). 추가로 5초 간 아군이 받는 피해를 30% 감소 시킵니다(최고 성급일 땐 60% 적용).'},
 32918: {'zh-CN': '★ 每施放4次神兵技能，对周围6米内敌人造成[基础伤害*500%]点伤害（必然命中）. ★ 根据周围20米内敌人的数量提升伤害，每个敌人可使本次伤害系数提升100%，最高提升1500%，敌人只包括：敌对的玩家及其宠物. ★ 满星时，会额外使目标眩晕4秒，添加时无视控制抗性',
  'ko': '★ 신병 스킬을 4회 시전할 때마다 주변 6미터 내의 적들에게 [기본 피해*500%]의 피해를 입히고(반드시 명중) . ★ 주변 20미터 내 적 수량에 따라 피해량이 증가합니다. 적마다 피해량이 100% 증가하며 최대 1500%까지 증가합니다. 적은 적 캐릭터 및 펫을 포함합니다.. ★ 최대 성급 달성 시 적을 4초 간 기절시키며 제어 면역을 무시합니다.'},
 25940: {'zh-CN': '★射程：8米  冷却：40秒. 对单个目标造成[基础伤害*{_x005f_x0001_}%+{_x005f_x0001_}]点伤害，并有{_x005f_x0001_}%几率使目标敌人在5秒进入失手状态，敌人在失手状态下施放武功时，有50%几率使敌人的随机1个友方眩晕2秒',
  'ko': '★사거리: 8m, 쿨타임: 40초. 단일 목표에게 [기본피해*{_x005f_x0001_}%+{_x005f_x0001_}]의 피해를 주며, {_x005f_x0001_}% 확률로 목표를 5초간 실수상태로 만든다. 적군은 실수 상태에서 무공 시전 시, 50%확률로 적군 자신의 아군 1명을 2초간 기절시킴'},
 32844: {'zh-CN': '★ 施放武功时获得魂语，上限500点，变身时释放所有魂语，使周围敌人进入失魂状态，期间敌人每次对玩家造成伤害时损失气血。并且自身攻击和防御提升，提升量和魂语数量有关，最多15%（满星魂语获取速度大幅提升，上限为1000点，敌人累计损血最多100%，属性提升最多30%）',
  'ko': '★ 무공 시전 시 최대 500 혼어 획득, 변신 시 모든 혼어를 시전하여 주위 상대 실혼, 실혼 상태에서 적군이 피해를 입힐 때 의 생명 감소 가능(최대치는 혼어 수량에 따라 정해짐). 자신의 공격 및 방어 최대 15% 증가(증가량은 혼어 수량에 따라 정해짐). (최고 성급에 달성하면 혼어 획득 속도 대폭 증가 및 최대 1000 획득, 적군 누적 생명 피해 최대 100%, 속성 증가 최대 30%)'},
 48774: {'zh-CN': '可选礼盒. 打开后可选择一种:幽灵虎魂魄×1，饕餮之魂×1，暹罗猫的铃铛×1，道奇缰绳×1，逐山龙鞍座×1，熊猫家谱×1，煞炼葫芦×1，火纹狼旗×1，仙云鼓风器×1，发条兔的零件×1，星鲲之角×1，孩子王×1，战象铠甲×1，玩具发条×1，莲心×1，伯乐相马经×50。',
  'ko': '선택상자. 유령호 영혼×1，도철 영혼×1，섬라묘 방울×1，도기 말고삐×1，축산용 안장×1，팬더 가보×1，살연 조롱박×1，화문염낭×1，선운고풍기×1，토미의 부품×1，성곤지각×1，아이왕×1，전상흉갑×1，장난감×1，연심×1，백락상마경×50중 1개를 선택하여 획득합니다.'},
 31808: {'zh-CN': '堕落的赏金猎人，刀大宝的上家。. 很早之前就知道金钵内藏有武功心法。在武僧被打伤后，他便已经盯上了其手中的金钵。不巧，重伤不治武僧和金钵一同被虎威镖局的人发现。更让他意想不到的是，虎威镖局的镖师并不知道金钵的秘密，反而将金钵交给了自己的手下，伪装成了铁匠的肖大宝。',
  'ko': '타락한 현상금 사냥꾼 도대보의 윗선. .  예전부터 금발 내 무공 심법이 있다는 걸 알고 있었습니다. 무승이 상처를 입은 뒤 무승이 갖고 있던 금발에 눈독을 들이기 시작했으나 무승이 호위표국 사람들에게 발각돼 버렸습니다.호위표국 사람들은 금발의 비밀을 모르고 있었고 금발을 자신의 수하에게 넘겨 대장간의 소대보로 위장하도록 했습니다.'},
 32820: {'zh-CN': '★ 新形象双子巫蛊刺（男女同体出战）. ★ 装备此神兵后气血+7500，攻击+500，防御+500（满星气血+10000，攻击+750，防御+750）. ★ 施放武功时有8%几率驱散周围敌人正面效果并延长负面效果2秒(满星后几率提升到12%，变身和非变身均可触发)',
  'ko': '★ 쌍둥이 무고척 남녀 캐릭터 동시 출전. ★ 장착 후 생명 +7500, 공격 +500, 방어 +500(최고 성급에 달성하면 생명 +10000, 공격 +750, 방어 +750). ★ 무공 시전 시 8% 확률로 2초간 주위 목표의 모든 버프효과 제거 및 디버프 효과 연장(최고 성급에 달성하면 12% 확률로 상향, 변신여부와 상관없이 발동)'},

In [3]:
import pandas as pd

df = pd.read_csv("태왕_단가_용어집.csv")
df

      zh-CN            ko
0        巨阙            거궐
1        帝阙            대궐
2        天阙            천문
3        潜龙            잠룡
4        战龙            군룡
...     ...           ...
16151  重火装甲          중화장갑
16152  异变蓝龙          이변남룡
16153  甜蜜爱巢  달콤한 사랑의 보금자리
16154  浪漫之旅          낭만여행
16155  梦幻浮排          몽환튜브

[16156 rows x 2 columns]

In [4]:
reference = df["zh-CN"].to_list()[:1000]  # 待翻译的句子
translation = df["ko"].to_list()[:1000]  # 标准的翻译

In [5]:
reference_pre = []
for text in reference:
    for glossary_id, glossary in glossary_dict.items():
        text = text.replace(glossary["zh-CN"], "<glossary_id={0}>".format(glossary_id))
    reference_pre.append(text)
reference_pre

['<glossary_id=35142>',
 '<glossary_id=99397>',
 '<glossary_id=99398>',
 '<glossary_id=99399>',
 '<glossary_id=99400>',
 '<glossary_id=99401>',
 '<glossary_id=99402>',
 '<glossary_id=99403>',
 '<glossary_id=99404>',
 '<glossary_id=99405>',
 '<glossary_id=99406>',
 '<glossary_id=99407>',
 '<glossary_id=99408>',
 '<glossary_id=99409>',
 '<glossary_id=99410>',
 '<glossary_id=99411>',
 '<glossary_id=99412>',
 '<glossary_id=99413>',
 '<glossary_id=99414>',
 '<glossary_id=99415>',
 '<glossary_id=99416>',
 '<glossary_id=88833>',
 '<glossary_id=99418>',
 '<glossary_id=99419>',
 '<glossary_id=99420>',
 '<glossary_id=99421>',
 '<glossary_id=99422>',
 '<glossary_id=99423>',
 '<glossary_id=61028>',
 '<glossary_id=99425>',
 '<glossary_id=99426>',
 '<glossary_id=99427>',
 '<glossary_id=100473>',
 '<glossary_id=99429>',
 '<glossary_id=99430>',
 '<glossary_id=99431>',
 '<glossary_id=99432>',
 '<glossary_id=99433>',
 '<glossary_id=99434>',
 '<glossary_id=99435>',
 '<glossary_id=99436>',
 '<glossary_id=99437>',
 '<glossary_id=99438>',
 '<glossary_id=11588>',
 '<glossary_id=11578>',
 '<glossary_id=99441>',
 '<glossary_id=99442>',
 '<glossary_id=99443>',
 '<glossary_id=99444>',
 '<glossary_id=99445>',
 '<glossary_id=99446>',
 '<glossary_id=99447>',
 '<glossary_id=99448>',
 '<glossary_id=99449>',
 '<glossary_id=99450>',
 '<glossary_id=99451>',
 '<glossary_id=99452>',
 '<glossary_id=99453>',
 '<glossary_id=99454>',
 '<glossary_id=99455>',
 '<glossary_id=99456>',
 '<glossary_id=99457>',
 '<glossary_id=99458>',
 '<glossary_id=99459>',
 '<glossary_id=99460>',
 '<glossary_id=99461>',
 '<glossary_id=99462>',
 '<glossary_id=99463>',
 '<glossary_id=99464>',
 '<glossary_id=99465>',
 '<glossary_id=99466>',
 '<glossary_id=99467>',
 '<glossary_id=99468>',
 '<glossary_id=99469>',
 '<glossary_id=99470>',
 '<glossary_id=99471>',
 '<glossary_id=99472>',
 '<glossary_id=99473>',
 '<glossary_id=99474>',
 '<glossary_id=99475>',
 '<glossary_id=99476>',
 '<glossary_id=99477>',
 '<glossary_id=99478>',
 '<glossary_id=99479>',
 '<glossary_id=99480>',
 '<glossary_id=99481>',
 '<glossary_id=99482>',
 '<glossary_id=64523>',
 '<glossary_id=99484>',
 '<glossary_id=99485>',
 '<glossary_id=99486>',
 '<glossary_id=99487>',
 '<glossary_id=99488>',
 '<glossary_id=99489>',
 '<glossary_id=90606>',
 '<glossary_id=99491>',
 '<glossary_id=99492>',
 '<glossary_id=62617>',
 '<glossary_id=62924>',
 '<glossary_id=62611>',
 '<glossary_id=99496>',
 '<glossary_id=62830>',
 '<glossary_id=99498>',
 '<glossary_id=99499>',
 '<glossary_id=99500>',
 '<glossary_id=91609>',
 '<glossary_id=99502>',
 '<glossary_id=99503>',
 '<glossary_id=99504>',
 '<glossary_id=99505>',
 '<glossary_id=99506>',
 '<glossary_id=99507>',
 '<glossary_id=99508>',
 '<glossary_id=99509>',
 '<glossary_id=99510>',
 '<glossary_id=99511>',
 '<glossary_id=99512>',
 '<glossary_id=95005>',
 '<glossary_id=96997>',
 '<glossary_id=99515>',
 '<glossary_id=59439>',
 '<glossary_id=64240>',
 '<glossary_id=62669>',
 '<glossary_id=99519>',
 '<glossary_id=99520>',
 '<glossary_id=99521>',
 '<glossary_id=99522>',
 '<glossary_id=99523>',
 '<glossary_id=99524>',
 '<glossary_id=99525>',
 '<glossary_id=99526>',
 '<glossary_id=99527>',
 '<glossary_id=60760>',
 '<glossary_id=99529>',
 '<glossary_id=60529>',
 '<glossary_id=99531>',
 '<glossary_id=97590>',
 '<glossary_id=99533>',
 '<glossary_id=99534>',
 '<glossary_id=99535>',
 '<glossary_id=99536>',
 '<glossary_id=99537>',
 '<glossary_id=99538>',
 '<glossary_id=1938>',
 '<glossary_id=99540>',
 '<glossary_id=99541>',
 '<glossary_id=99542>',
 '<glossary_id=62070>',
 '<glossary_id=99544>',
 '<glossary_id=99545>',
 '<glossary_id=99546>',
 '<glossary_id=99547>',
 '<glossary_id=99548>',
 '<glossary_id=99549>',
 '<glossary_id=99550>',
 '<glossary_id=99551>',
 '<glossary_id=99552>',
 '<glossary_id=99553>',
 '<glossary_id=99554>',
 '<glossary_id=99555>',
 '<glossary_id=99556>',
 '<glossary_id=99557>',
 '<glossary_id=99558>',
 '<glossary_id=99559>',
 '<glossary_id=99560>',
 '<glossary_id=99561>',
 '<glossary_id=99562>',
 '<glossary_id=99563>',
 '<glossary_id=99564>',
 '<glossary_id=99565>',
 '<glossary_id=99566>',
 '<glossary_id=99567>',
 '<glossary_id=99568>',
 '<glossary_id=99569>',
 '<glossary_id=99570>',
 '<glossary_id=99571>',
 '<glossary_id=99572>',
 '<glossary_id=99573>',
 '<glossary_id=99574>',
 '<glossary_id=99575>',
 '<glossary_id=99576>',
 '<glossary_id=99577>',
 '<glossary_id=99578>',
 '<glossary_id=99579>',
 '<glossary_id=99580>',
 '<glossary_id=99581>',
 '<glossary_id=99582>',
 '<glossary_id=99583>',
 '<glossary_id=99584>',
 '<glossary_id=104852>',
 '<glossary_id=99586>',
 '<glossary_id=99587>',
 '<glossary_id=99588>',
 '<glossary_id=99589>',
 '<glossary_id=99590>',
 '<glossary_id=99591>',
 '<glossary_id=99592>',
 '<glossary_id=99593>',
 '<glossary_id=99594>',
 '<glossary_id=99595>',
 '<glossary_id=99596>',
 '<glossary_id=24787>',
 '<glossary_id=99598>',
 '<glossary_id=99599>',
 '<glossary_id=91156>',
 '<glossary_id=99601>',
 '<glossary_id=11158>',
 '<glossary_id=99603>',
 '<glossary_id=99604>',
 '<glossary_id=99605>',
 '<glossary_id=99606>',
 '<glossary_id=99607>',
 '<glossary_id=99608>',
 '<glossary_id=99609>',
 '<glossary_id=99610>',
 '<glossary_id=99611>',
 '<glossary_id=99612>',
 '<glossary_id=99613>',
 '<glossary_id=99614>',
 '<glossary_id=99615>',
 '<glossary_id=99616>',
 '<glossary_id=99617>',
 '<glossary_id=99618>',
 '<glossary_id=99619>',
 '<glossary_id=99620>',
 '<glossary_id=99621>',
 '<glossary_id=99622>',
 '<glossary_id=99623>',
 '<glossary_id=99624>',
 '<glossary_id=99625>',
 '<glossary_id=99626>',
 '<glossary_id=99627>',
 '<glossary_id=99628>',
 '<glossary_id=99629>',
 '<glossary_id=99630>',
 '<glossary_id=62958>',
 '<glossary_id=99632>',
 '<glossary_id=99633>',
 '<glossary_id=24853>',
 '<glossary_id=99635>',
 '<glossary_id=99636>',
 '<glossary_id=99637>',
 '<glossary_id=99638>',
 '<glossary_id=99639>',
 '<glossary_id=99640>',
 '<glossary_id=99641>',
 '<glossary_id=99642>',
 '<glossary_id=99643>',
 '<glossary_id=99644>',
 '<glossary_id=99645>',
 '<glossary_id=99646>',
 '<glossary_id=99647>',
 '<glossary_id=99648>',
 '<glossary_id=99649>',
 '<glossary_id=99650>',
 '<glossary_id=99651>',
 '<glossary_id=99652>',
 '<glossary_id=99653>',
 '<glossary_id=99654>',
 '<glossary_id=99655>',
 '<glossary_id=99656>',
 '<glossary_id=99657>',
 '<glossary_id=99658>',
 '<glossary_id=99659>',
 '<glossary_id=99660>',
 '<glossary_id=99661>',
 '<glossary_id=99662>',
 '<glossary_id=99663>',
 '<glossary_id=61520>',
 '<glossary_id=99665>',
 '<glossary_id=99666>',
 '<glossary_id=99667>',
 '<glossary_id=99668>',
 '<glossary_id=99669>',
 '<glossary_id=99670>',
 '<glossary_id=99671>',
 '<glossary_id=99672>',
 '<glossary_id=99673>',
 '<glossary_id=99674>',
 '<glossary_id=62047>',
 '<glossary_id=99676>',
 '<glossary_id=99677>',
 '<glossary_id=99678>',
 '<glossary_id=99679>',
 '<glossary_id=99680>',
 '<glossary_id=99681>',
 '<glossary_id=99682>',
 '<glossary_id=99683>',
 '<glossary_id=99684>',
 '<glossary_id=99685>',
 '<glossary_id=99686>',
 '<glossary_id=99687>',
 '<glossary_id=99688>',
 '<glossary_id=99689>',
 '<glossary_id=99690>',
 '<glossary_id=99691>',
 '<glossary_id=99692>',
 '<glossary_id=99693>',
 '<glossary_id=99694>',
 '<glossary_id=99695>',
 '<glossary_id=34361>',
 '<glossary_id=99697>',
 '<glossary_id=63198>',
 '<glossary_id=99699>',
 '<glossary_id=99700>',
 '<glossary_id=99701>',
 '<glossary_id=99702>',
 '<glossary_id=99703>',
 '<glossary_id=99704>',
 '<glossary_id=99705>',
 '<glossary_id=99706>',
 '<glossary_id=99707>',
 '<glossary_id=99708>',
 '<glossary_id=99709>',
 '<glossary_id=99710>',
 '<glossary_id=99711>',
 '<glossary_id=99712>',
 '<glossary_id=99713>',
 '<glossary_id=99714>',
 '<glossary_id=99715>',
 '<glossary_id=99716>',
 '<glossary_id=99717>',
 '<glossary_id=99718>',
 '<glossary_id=99719>',
 '<glossary_id=99720>',
 '<glossary_id=99721>',
 '<glossary_id=99722>',
 '<glossary_id=62165>',
 '<glossary_id=99724>',
 '<glossary_id=99725>',
 '<glossary_id=99726>',
 '<glossary_id=99727>',
 '<glossary_id=99728>',
 '<glossary_id=59820>',
 '<glossary_id=99730>',
 '<glossary_id=99731>',
 '<glossary_id=99732>',
 '<glossary_id=89714>',
 '<glossary_id=99734>',
 '<glossary_id=99735>',
 '<glossary_id=99736>',
 '<glossary_id=99737>',
 '<glossary_id=99738>',
 '<glossary_id=99739>',
 '<glossary_id=99740>',
 '<glossary_id=99741>',
 '<glossary_id=99742>',
 '<glossary_id=99743>',
 '<glossary_id=99744>',
 '<glossary_id=99745>',
 '<glossary_id=99746>',
 '<glossary_id=99747>',
 '<glossary_id=99748>',
 '<glossary_id=99749>',
 '<glossary_id=99750>',
 '<glossary_id=99751>',
 '<glossary_id=99752>',
 '<glossary_id=99753>',
 '<glossary_id=99754>',
 '<glossary_id=99755>',
 '<glossary_id=99756>',
 '<glossary_id=99757>',
 '<glossary_id=99758>',
 '<glossary_id=99759>',
 '<glossary_id=99760>',
 '<glossary_id=91239>',
 '<glossary_id=99762>',
 '<glossary_id=99763>',
 '<glossary_id=99764>',
 '<glossary_id=99765>',
 '<glossary_id=99766>',
 '<glossary_id=99767>',
 '<glossary_id=99768>',
 '<glossary_id=99769>',
 '<glossary_id=99770>',
 '<glossary_id=99771>',
 '<glossary_id=99772>',
 '<glossary_id=99773>',
 '<glossary_id=99774>',
 '<glossary_id=99775>',
 '<glossary_id=99776>',
 '<glossary_id=99777>',
 '<glossary_id=99778>',
 '<glossary_id=99779>',
 '<glossary_id=99780>',
 '<glossary_id=99781>',
 '<glossary_id=99782>',
 '<glossary_id=99783>',
 '<glossary_id=99784>',
 '<glossary_id=99785>',
 '<glossary_id=99786>',
 '<glossary_id=99787>',
 '<glossary_id=99788>',
 '<glossary_id=99789>',
 '<glossary_id=99790>',
 '<glossary_id=99791>',
 '<glossary_id=99792>',
 '<glossary_id=99793>',
 '<glossary_id=99794>',
 '<glossary_id=99795>',
 '<glossary_id=99796>',
 '<glossary_id=99797>',
 '<glossary_id=99798>',
 '<glossary_id=99799>',
 '<glossary_id=99800>',
 '<glossary_id=99801>',
 '<glossary_id=99802>',
 '<glossary_id=99803>',
 '<glossary_id=99804>',
 '<glossary_id=99805>',
 '<glossary_id=99806>',
 '<glossary_id=99807>',
 '<glossary_id=99808>',
 '<glossary_id=99809>',
 '<glossary_id=99810>',
 '<glossary_id=99811>',
 '<glossary_id=99812>',
 '<glossary_id=99813>',
 '<glossary_id=99814>',
 '<glossary_id=99815>',
 '<glossary_id=99816>',
 '<glossary_id=99817>',
 '<glossary_id=99818>',
 '<glossary_id=99819>',
 '<glossary_id=99820>',
 '<glossary_id=99821>',
 '<glossary_id=99822>',
 '<glossary_id=99823>',
 '<glossary_id=99824>',
 '<glossary_id=99825>',
 '<glossary_id=99826>',
 '<glossary_id=99827>',
 '<glossary_id=99828>',
 '<glossary_id=99829>',
 '<glossary_id=99830>',
 '<glossary_id=99831>',
 '<glossary_id=99832>',
 '<glossary_id=99833>',
 '<glossary_id=92045>',
 '<glossary_id=99835>',
 '<glossary_id=99836>',
 '<glossary_id=99837>',
 '<glossary_id=99838>',
 '<glossary_id=99839>',
 '<glossary_id=99840>',
 '<glossary_id=63785>',
 '<glossary_id=99842>',
 '<glossary_id=99843>',
 '<glossary_id=99844>',
 '<glossary_id=99845>',
 '<glossary_id=6298>',
 '<glossary_id=99847>',
 '<glossary_id=99848>',
 '<glossary_id=99849>',
 '<glossary_id=95126>',
 '<glossary_id=99851>',
 '<glossary_id=96662>',
 '<glossary_id=99853>',
 '<glossary_id=99854>',
 '<glossary_id=99855>',
 '<glossary_id=99856>',
 '<glossary_id=99857>',
 '<glossary_id=99858>',
 '<glossary_id=99859>',
 '<glossary_id=99860>',
 '<glossary_id=99861>',
 '<glossary_id=99862>',
 '<glossary_id=99863>',
 '<glossary_id=99864>',
 '<glossary_id=99865>',
 '<glossary_id=99866>',
 '<glossary_id=99867>',
 '<glossary_id=99868>',
 '<glossary_id=99869>',
 '<glossary_id=99870>',
 '<glossary_id=99871>',
 '<glossary_id=99872>',
 '<glossary_id=99873>',
 '<glossary_id=99874>',
 '<glossary_id=99875>',
 '<glossary_id=99876>',
 '<glossary_id=99877>',
 '<glossary_id=99878>',
 '<glossary_id=99879>',
 '<glossary_id=99880>',
 '<glossary_id=99881>',
 '<glossary_id=99882>',
 '<glossary_id=99883>',
 '<glossary_id=99884>',
 '<glossary_id=99885>',
 '<glossary_id=99886>',
 '<glossary_id=99887>',
 '<glossary_id=99888>',
 '<glossary_id=99889>',
 '<glossary_id=99890>',
 '<glossary_id=99891>',
 '<glossary_id=99892>',
 '<glossary_id=99893>',
 '<glossary_id=99894>',
 '<glossary_id=99895>',
 '<glossary_id=99896>',
 '<glossary_id=99897>',
 '<glossary_id=99898>',
 '<glossary_id=99899>',
 '<glossary_id=99900>',
 '<glossary_id=99901>',
 '<glossary_id=99902>',
 '<glossary_id=99903>',
 '<glossary_id=99904>',
 '<glossary_id=99905>',
 '<glossary_id=99906>',
 '<glossary_id=89600>',
 '<glossary_id=99908>',
 '<glossary_id=99909>',
 '<glossary_id=111103>',
 '<glossary_id=99911>',
 '<glossary_id=99912>',
 '<glossary_id=99913>',
 '<glossary_id=99914>',
 '<glossary_id=99915>',
 '<glossary_id=99916>',
 '<glossary_id=99917>',
 '<glossary_id=99918>',
 '<glossary_id=99919>',
 '<glossary_id=99920>',
 '<glossary_id=99921>',
 '<glossary_id=99922>',
 '<glossary_id=99923>',
 '<glossary_id=99924>',
 '<glossary_id=99925>',
 '<glossary_id=99926>',
 '<glossary_id=99927>',
 '<glossary_id=99928>',
 '<glossary_id=99929>',
 '<glossary_id=99930>',
 '<glossary_id=99931>',
 '<glossary_id=99932>',
 '<glossary_id=99933>',
 '<glossary_id=99934>',
 '<glossary_id=99935>',
 '<glossary_id=62339>',
 '<glossary_id=99937>',
 '<glossary_id=99938>',
 '<glossary_id=99939>',
 '<glossary_id=99940>',
 '<glossary_id=21652>',
 '<glossary_id=99942>',
 '<glossary_id=99943>',
 '<glossary_id=99944>',
 '<glossary_id=99945>',
 '<glossary_id=99946>',
 '<glossary_id=99947>',
 '<glossary_id=99948>',
 '<glossary_id=88997>',
 '<glossary_id=99950>',
 '<glossary_id=99951>',
 '<glossary_id=99952>',
 '<glossary_id=3401>',
 '<glossary_id=99954>',
 '<glossary_id=99955>',
 '<glossary_id=99956>',
 '<glossary_id=99957>',
 '<glossary_id=99958>',
 '<glossary_id=99959>',
 '<glossary_id=99960>',
 '<glossary_id=99961>',
 '<glossary_id=99962>',
 '<glossary_id=99963>',
 '<glossary_id=99964>',
 '<glossary_id=99965>',
 '<glossary_id=99966>',
 '<glossary_id=99967>',
 '<glossary_id=99968>',
 '<glossary_id=94738>',
 '<glossary_id=99970>',
 '<glossary_id=99971>',
 '<glossary_id=99972>',
 '<glossary_id=99973>',
 '<glossary_id=99974>',
 '<glossary_id=99975>',
 '<glossary_id=99976>',
 '<glossary_id=99977>',
 '<glossary_id=99978>',
 '<glossary_id=99979>',
 '<glossary_id=99980>',
 '<glossary_id=99981>',
 '<glossary_id=99982>',
 '<glossary_id=99983>',
 '<glossary_id=99984>',
 '<glossary_id=99985>',
 '<glossary_id=99986>',
 '<glossary_id=99987>',
 '<glossary_id=99988>',
 '<glossary_id=99989>',
 '<glossary_id=99990>',
 '<glossary_id=99991>',
 '<glossary_id=99992>',
 '<glossary_id=99993>',
 '<glossary_id=99994>',
 '<glossary_id=99995>',
 '<glossary_id=99996>',
 '<glossary_id=99997>',
 '<glossary_id=99998>',
 '<glossary_id=99999>',
 '<glossary_id=100000>',
 '<glossary_id=100001>',
 '<glossary_id=100002>',
 '<glossary_id=100003>',
 '<glossary_id=100004>',
 '<glossary_id=100005>',
 '<glossary_id=100006>',
 '<glossary_id=100007>',
 '<glossary_id=100008>',
 '<glossary_id=100009>',
 '<glossary_id=100010>',
 '<glossary_id=100011>',
 '<glossary_id=100012>',
 '<glossary_id=100013>',
 '<glossary_id=100014>',
 '<glossary_id=100015>',
 '<glossary_id=100016>',
 '<glossary_id=100017>',
 '<glossary_id=100018>',
 '<glossary_id=100019>',
 '<glossary_id=94927>',
 '<glossary_id=100021>',
 '<glossary_id=100022>',
 '<glossary_id=100023>',
 '<glossary_id=100024>',
 '<glossary_id=100025>',
 '<glossary_id=100026>',
 '<glossary_id=100027>',
 '<glossary_id=100028>',
 '<glossary_id=100029>',
 '<glossary_id=100030>',
 '<glossary_id=100031>',
 '<glossary_id=100032>',
 '<glossary_id=100033>',
 '<glossary_id=100034>',
 '<glossary_id=100035>',
 '<glossary_id=100036>',
 '<glossary_id=100037>',
 '<glossary_id=100038>',
 '<glossary_id=100039>',
 '<glossary_id=100040>',
 '<glossary_id=100041>',
 '<glossary_id=100042>',
 '<glossary_id=100043>',
 '<glossary_id=100044>',
 '<glossary_id=100045>',
 '<glossary_id=100046>',
 '<glossary_id=100047>',
 '<glossary_id=100048>',
 '<glossary_id=100049>',
 '<glossary_id=100050>',
 '<glossary_id=100051>',
 '<glossary_id=100052>',
 '<glossary_id=100053>',
 '<glossary_id=100054>',
 '<glossary_id=100055>',
 '<glossary_id=31391>',
 '<glossary_id=100057>',
 '<glossary_id=100058>',
 '<glossary_id=100059>',
 '<glossary_id=100060>',
 '<glossary_id=100061>',
 '<glossary_id=100062>',
 '<glossary_id=100063>',
 '<glossary_id=100064>',
 '<glossary_id=100065>',
 '<glossary_id=100066>',
 '<glossary_id=100067>',
 '<glossary_id=100068>',
 '<glossary_id=100069>',
 '<glossary_id=100070>',
 '<glossary_id=100071>',
 '<glossary_id=100072>',
 '<glossary_id=100073>',
 '<glossary_id=100074>',
 '<glossary_id=100075>',
 '<glossary_id=100076>',
 '<glossary_id=100077>',
 '<glossary_id=100078>',
 '<glossary_id=100079>',
 '<glossary_id=100080>',
 '<glossary_id=100081>',
 '<glossary_id=100082>',
 '<glossary_id=100083>',
 '<glossary_id=100084>',
 '<glossary_id=100085>',
 '<glossary_id=100086>',
 '<glossary_id=100087>',
 '<glossary_id=100088>',
 '<glossary_id=100089>',
 '<glossary_id=100090>',
 '<glossary_id=100091>',
 '<glossary_id=100092>',
 '<glossary_id=100093>',
 '<glossary_id=100094>',
 '<glossary_id=100095>',
 '<glossary_id=100096>',
 '<glossary_id=100097>',
 '<glossary_id=100098>',
 '<glossary_id=100099>',
 '<glossary_id=100100>',
 '<glossary_id=100101>',
 '<glossary_id=1236>',
 '<glossary_id=100103>',
 '<glossary_id=100104>',
 '<glossary_id=100105>',
 '<glossary_id=100106>',
 '<glossary_id=100107>',
 '<glossary_id=100108>',
 '<glossary_id=100109>',
 '<glossary_id=100110>',
 '<glossary_id=100111>',
 '<glossary_id=100112>',
 '<glossary_id=100113>',
 '<glossary_id=100114>',
 '<glossary_id=100115>',
 '<glossary_id=100116>',
 '<glossary_id=100117>',
 '<glossary_id=100118>',
 '<glossary_id=100119>',
 '<glossary_id=100120>',
 '<glossary_id=100121>',
 '<glossary_id=100122>',
 '<glossary_id=100123>',
 '<glossary_id=100124>',
 '<glossary_id=100125>',
 '<glossary_id=100126>',
 '<glossary_id=100127>',
 '<glossary_id=100128>',
 '<glossary_id=100129>',
 '<glossary_id=100130>',
 '<glossary_id=100131>',
 '<glossary_id=100132>',
 '<glossary_id=100133>',
 '<glossary_id=100134>',
 '<glossary_id=100135>',
 '<glossary_id=100136>',
 '<glossary_id=100137>',
 '<glossary_id=100138>',
 '<glossary_id=100139>',
 '<glossary_id=100140>',
 '<glossary_id=100141>',
 '<glossary_id=100142>',
 '<glossary_id=100143>',
 '<glossary_id=100144>',
 '<glossary_id=100145>',
 '<glossary_id=100146>',
 '<glossary_id=100147>',
 '<glossary_id=100148>',
 '<glossary_id=100149>',
 '<glossary_id=100150>',
 '<glossary_id=100151>',
 '<glossary_id=100152>',
 '<glossary_id=100153>',
 '<glossary_id=100154>',
 '<glossary_id=100155>',
 '<glossary_id=100156>',
 '<glossary_id=100157>',
 '<glossary_id=100158>',
 '<glossary_id=100159>',
 '<glossary_id=100160>',
 '<glossary_id=100161>',
 '<glossary_id=100162>',
 '<glossary_id=100163>',
 '<glossary_id=100164>',
 '<glossary_id=100165>',
 '<glossary_id=100166>',
 '<glossary_id=100167>',
 '<glossary_id=100168>',
 '<glossary_id=100169>',
 '<glossary_id=100170>',
 '<glossary_id=100171>',
 '<glossary_id=100172>',
 '<glossary_id=100173>',
 '<glossary_id=100174>',
 '<glossary_id=100175>',
 '<glossary_id=100176>',
 '<glossary_id=100177>',
 '<glossary_id=100178>',
 '<glossary_id=100179>',
 '<glossary_id=100180>',
 '<glossary_id=100181>',
 '<glossary_id=100182>',
 '<glossary_id=100183>',
 '<glossary_id=100184>',
 '<glossary_id=100185>',
 '<glossary_id=100186>',
 '<glossary_id=100187>',
 '<glossary_id=100188>',
 '<glossary_id=100189>',
 '<glossary_id=100190>',
 '<glossary_id=100191>',
 '<glossary_id=100192>',
 '<glossary_id=100193>',
 '<glossary_id=100194>',
 '<glossary_id=100195>',
 '<glossary_id=100196>',
 '<glossary_id=100197>',
 '<glossary_id=100198>',
 '<glossary_id=100199>',
 '<glossary_id=100200>',
 '<glossary_id=100201>',
 '<glossary_id=100202>',
 '<glossary_id=100203>',
 '<glossary_id=100204>',
 '<glossary_id=100205>',
 '<glossary_id=100206>',
 '<glossary_id=100207>',
 '<glossary_id=100208>',
 '<glossary_id=100209>',
 '<glossary_id=62699>',
 '<glossary_id=100211>',
 '<glossary_id=100212>',
 '<glossary_id=100213>',
 '<glossary_id=100214>',
 '<glossary_id=100215>',
 '<glossary_id=100216>',
 '<glossary_id=100217>',
 '<glossary_id=100218>',
 '<glossary_id=100219>',

In [6]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 加载model,tokenizer
custom_model_name = "fine-tuned-models/nllb-200-3.3B/zh2ko_0913"

model = AutoModelForSeq2SeqLM.from_pretrained(custom_model_name)
tokenizer = AutoTokenizer.from_pretrained(custom_model_name)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [7]:
from transformers import pipeline

translator = pipeline("translation", model=model, tokenizer=tokenizer,
                      src_lang=tokenizer.src_lang,
                      tgt_lang=tokenizer.tgt_lang,
                      device_map="auto", max_length=400)
# translator = pipeline("translation", model=model, tokenizer=tokenizer,
#                       src_lang=tokenizer.src_lang,
#                       tgt_lang=tokenizer.tgt_lang,
#                       device="cuda:0", max_length=400)

In [8]:
translated = translator(reference_pre)
translated_text = [item['translation_text'] for item in translated]
translated_text

['<glossary_id=35142>',
 '<glossary_id=99397>',
 '<glossary_id=99398>',
 '<glossary_id=99399>',
 '<glossary_id=99400>',
 '<glossary_id=99401>',
 '<glossary_id=99402>',
 '<glossary_id=99403>',
 '<glossary_id=99404>',
 '<glossary_id=99405>',
 '<glossary_id=99406>',
 '<glossary_id=99407>',
 '<glossary_id=99408>',
 '<glossary_id=99409>',
 '<glossary_id=99410>',
 '<glossary_id=99411>',
 '<glossary_id=99412>',
 '<glossary_id=99413>',
 '<glossary_id=99414>',
 '<glossary_id=99415>',
 '<glossary_id=99416>',
 '<glossary_id=88833>',
 '<glossary_id=99418>',
 '<glossary_id=99419>',
 '<glossary_id=99420>',
 '<glossary_id=99421>',
 '<glossary_id=99422>',
 '<glossary_id=99423>',
 '<glossary_id=61028>',
 '<glossary_id=99425>',
 '<glossary_id=99426>',
 '<glossary_id=99427>',
 '<glossary_id=100473>',
 '<glossary_id=99429>',
 '<glossary_id=99430>',
 '<glossary_id=99431>',
 '<glossary_id=99432>',
 '<glossary_id=99433>',
 '<glossary_id=99434>',
 '<glossary_id=99435>',
 '<glossary_id=99436>',
 '<glossary_id=99437>',
 '<glossary_id=99438>',
 '<glossary_id=11588>',
 '<glossary_id=11578>',
 '<glossary_id=99441>',
 '<glossary_id=99442>',
 '<glossary_id=99443>',
 '<glossary_id=99444>',
 '<glossary_id=99445>',
 '<glossary_id=99446>',
 '<glossary_id=99447>',
 '<glossary_id=99448>',
 '<glossary_id=99449>',
 '<glossary_id=99450>',
 '<glossary_id=99451>',
 '<glossary_id=99452>',
 '<glossary_id=99453>',
 '<glossary_id=99454>',
 '<glossary_id=99455>',
 '<glossary_id=99456>',
 '<glossary_id=99457>',
 '<glossary_id=99458>',
 '<glossary_id=99459>',
 '<glossary_id=99460>',
 '<glossary_id=99461>',
 '<glossary_id=99462>',
 '<glossary_id=99463>',
 '<glossary_id=99464>',
 '<glossary_id=99465>',
 '<glossary_id=99466>',
 '<glossary_id=99467>',
 '<glossary_id=99468>',
 '<glossary_id=99469>',
 '<glossary_id=99470>',
 '<glossary_id=99471>',
 '<glossary_id=99472>',
 '<glossary_id=99473>',
 '<glossary_id=99474>',
 '<glossary_id=99475>',
 '<glossary_id=99476>',
 '<glossary_id=99477>',
 '<glossary_id=99478>',
 '<glossary_id=99479>',
 '<glossary_id=99480>',
 '<glossary_id=99481>',
 '<glossary_id=99482>',
 '<glossary_id=64523>',
 '<glossary_id=99484>',
 '<glossary_id=99485>',
 '<glossary_id=99486>',
 '<glossary_id=99487>',
 '<glossary_id=99488>',
 '<glossary_id=99489>',
 '<glossary_id=90606>',
 '<glossary_id=99491>',
 '<glossary_id=99492>',
 '<glossary_id=62617>',
 '<glossary_id=62924>',
 '<glossary_id=62611>',
 '<glossary_id=99496>',
 '<glossary_id=62830>',
 '<glossary_id=99498>',
 '<glossary_id=99499>',
 '<glossary_id=99500>',
 '<glossary_id=91609>',
 '<glossary_id=99502>',
 '<glossary_id=99503>',
 '<glossary_id=99504>',
 '<glossary_id=99505>',
 '<glossary_id=99506>',
 '<glossary_id=99507>',
 '<glossary_id=99508>',
 '<glossary_id=99509>',
 '<glossary_id=99510>',
 '<glossary_id=99511>',
 '<glossary_id=99512>',
 '<glossary_id=95005>',
 '<glossary_id=96997>',
 '<glossary_id=99515>',
 '<glossary_id=59439>',
 '<glossary_id=64240>',
 '<glossary_id=62669>',
 '<glossary_id=99519>',
 '<glossary_id=99520>',
 '<glossary_id=99521>',
 '<glossary_id=99522>',
 '<glossary_id=99523>',
 '<glossary_id=99524>',
 '<glossary_id=99525>',
 '<glossary_id=99526>',
 '<glossary_id=99527>',
 '<glossary_id=60760>',
 '<glossary_id=99529>',
 '<glossary_id=60529>',
 '<glossary_id=99531>',
 '<glossary_id=97590>',
 '<glossary_id=99533>',
 '<glossary_id=99534>',
 '<glossary_id=99535>',
 '<glossary_id=99536>',
 '<glossary_id=99537>',
 '<glossary_id=99538>',
 '<glossary_id=1938>',
 '<glossary_id=99540>',
 '<glossary_id=99541>',
 '<glossary_id=99542>',
 '<glossary_id=62070>',
 '<glossary_id=99544>',
 '<glossary_id=99545>',
 '<glossary_id=99546>',
 '<glossary_id=99547>',
 '<glossary_id=99548>',
 '<glossary_id=99549>',
 '<glossary_id=99550>',
 '<glossary_id=99551>',
 '<glossary_id=99552>',
 '<glossary_id=99553>',
 '<glossary_id=99554>',
 '<glossary_id=99555>',
 '<glossary_id=99556>',
 '<glossary_id=99557>',
 '<glossary_id=99558>',
 '<glossary_id=99559>',
 '<glossary_id=99560>',
 '<glossary_id=99561>',
 '<glossary_id=99562>',
 '<glossary_id=99563>',
 '<glossary_id=99564>',
 '<glossary_id=99565>',
 '<glossary_id=99566>',
 '<glossary_id=99567>',
 '<glossary_id=99568>',
 '<glossary_id=99569>',
 '<glossary_id=99570>',
 '<glossary_id=99571>',
 '<glossary_id=99572>',
 '<glossary_id=99573>',
 '<glossary_id=99574>',
 '<glossary_id=99575>',
 '<glossary_id=99576>',
 '<glossary_id=99577>',
 '<glossary_id=99578>',
 '<glossary_id=99579>',
 '<glossary_id=99580>',
 '<glossary_id=99581>',
 '<glossary_id=99582>',
 '<glossary_id=99583>',
 '<glossary_id=99584>',
 '<glossary_id=104852>',
 '<glossary_id=99586>',
 '<glossary_id=99587>',
 '<glossary_id=99588>',
 '<glossary_id=99589>',
 '<glossary_id=99590>',
 '<glossary_id=99591>',
 '<glossary_id=99592>',
 '<glossary_id=99593>',
 '<glossary_id=99594>',
 '<glossary_id=99595>',
 '<glossary_id=99596>',
 '<glossary_id=24787>',
 '<glossary_id=99598>',
 '<glossary_id=99599>',
 '<glossary_id=91156>',
 '<glossary_id=99601>',
 '<glossary_id=11158>',
 '<glossary_id=99603>',
 '<glossary_id=99604>',
 '<glossary_id=99605>',
 '<glossary_id=99606>',
 '<glossary_id=99607>',
 '<glossary_id=99608>',
 '<glossary_id=99609>',
 '<glossary_id=99610>',
 '<glossary_id=99611>',
 '<glossary_id=99612>',
 '<glossary_id=99613>',
 '<glossary_id=99614>',
 '<glossary_id=99615>',
 '<glossary_id=99616>',
 '<glossary_id=99617>',
 '<glossary_id=99618>',
 '<glossary_id=99619>',
 '<glossary_id=99620>',
 '<glossary_id=99621>',
 '<glossary_id=99622>',
 '<glossary_id=99623>',
 '<glossary_id=99624>',
 '<glossary_id=99625>',
 '<glossary_id=99626>',
 '<glossary_id=99627>',
 '<glossary_id=99628>',
 '<glossary_id=99629>',
 '<glossary_id=99630>',
 '<glossary_id=62958>',
 '<glossary_id=99632>',
 '<glossary_id=99633>',
 '<glossary_id=24853>',
 '<glossary_id=99635>',
 '<glossary_id=99636>',
 '<glossary_id=99637>',
 '<glossary_id=99638>',
 '<glossary_id=99639>',
 '<glossary_id=99640>',
 '<glossary_id=99641>',
 '<glossary_id=99642>',
 '<glossary_id=99643>',
 '<glossary_id=99644>',
 '<glossary_id=99645>',
 '<glossary_id=99646>',
 '<glossary_id=99647>',
 '<glossary_id=99648>',
 '<glossary_id=99649>',
 '<glossary_id=99650>',
 '<glossary_id=99651>',
 '<glossary_id=99652>',
 '<glossary_id=99653>',
 '<glossary_id=99654>',
 '<glossary_id=99655>',
 '<glossary_id=99656>',
 '<glossary_id=99657>',
 '<glossary_id=99658>',
 '<glossary_id=99659>',
 '<glossary_id=99660>',
 '<glossary_id=99661>',
 '<glossary_id=99662>',
 '<glossary_id=99663>',
 '<glossary_id=61520>',
 '<glossary_id=99665>',
 '<glossary_id=99666>',
 '<glossary_id=99667>',
 '<glossary_id=99668>',
 '<glossary_id=99669>',
 '<glossary_id=99670>',
 '<glossary_id=99671>',
 '<glossary_id=99672>',
 '<glossary_id=99673>',
 '<glossary_id=99674>',
 '<glossary_id=62047>',
 '<glossary_id=99676>',
 '<glossary_id=99677>',
 '<glossary_id=99678>',
 '<glossary_id=99679>',
 '<glossary_id=99680>',
 '<glossary_id=99681>',
 '<glossary_id=99682>',
 '<glossary_id=99683>',
 '<glossary_id=99684>',
 '<glossary_id=99685>',
 '<glossary_id=99686>',
 '<glossary_id=99687>',
 '<glossary_id=99688>',
 '<glossary_id=99689>',
 '<glossary_id=99690>',
 '<glossary_id=99691>',
 '<glossary_id=99692>',
 '<glossary_id=99693>',
 '<glossary_id=99694>',
 '<glossary_id=99695>',
 '<glossary_id=34361>',
 '<glossary_id=99697>',
 '<glossary_id=63198>',
 '<glossary_id=99699>',
 '<glossary_id=99700>',
 '<glossary_id=99701>',
 '<glossary_id=99702>',
 '<glossary_id=99703>',
 '<glossary_id=99704>',
 '<glossary_id=99705>',
 '<glossary_id=99706>',
 '<glossary_id=99707>',
 '<glossary_id=99708>',
 '<glossary_id=99709>',
 '<glossary_id=99710>',
 '<glossary_id=99711>',
 '<glossary_id=99712>',
 '<glossary_id=99713>',
 '<glossary_id=99714>',
 '<glossary_id=99715>',
 '<glossary_id=99716>',
 '<glossary_id=99717>',
 '<glossary_id=99718>',
 '<glossary_id=99719>',
 '<glossary_id=99720>',
 '<glossary_id=99721>',
 '<glossary_id=99722>',
 '<glossary_id=62165>',
 '<glossary_id=99724>',
 '<glossary_id=99725>',
 '<glossary_id=99726>',
 '<glossary_id=99727>',
 '<glossary_id=99728>',
 '<glossary_id=59820>',
 '<glossary_id=99730>',
 '<glossary_id=99731>',
 '<glossary_id=99732>',
 '<glossary_id=89714>',
 '<glossary_id=99734>',
 '<glossary_id=99735>',
 '<glossary_id=99736>',
 '<glossary_id=99737>',
 '<glossary_id=99738>',
 '<glossary_id=99739>',
 '<glossary_id=99740>',
 '<glossary_id=99741>',
 '<glossary_id=99742>',
 '<glossary_id=99743>',
 '<glossary_id=99744>',
 '<glossary_id=99745>',
 '<glossary_id=99746>',
 '<glossary_id=99747>',
 '<glossary_id=99748>',
 '<glossary_id=99749>',
 '<glossary_id=99750>',
 '<glossary_id=99751>',
 '<glossary_id=99752>',
 '<glossary_id=99753>',
 '<glossary_id=99754>',
 '<glossary_id=99755>',
 '<glossary_id=99756>',
 '<glossary_id=99757>',
 '<glossary_id=99758>',
 '<glossary_id=99759>',
 '<glossary_id=99760>',
 '<glossary_id=91239>',
 '<glossary_id=99762>',
 '<glossary_id=99763>',
 '<glossary_id=99764>',
 '<glossary_id=99765>',
 '<glossary_id=99766>',
 '<glossary_id=99767>',
 '<glossary_id=99768>',
 '<glossary_id=99769>',
 '<glossary_id=99770>',
 '<glossary_id=99771>',
 '<glossary_id=99772>',
 '<glossary_id=99773>',
 '<glossary_id=99774>',
 '<glossary_id=99775>',
 '<glossary_id=99776>',
 '<glossary_id=99777>',
 '<glossary_id=99778>',
 '<glossary_id=99779>',
 '<glossary_id=99780>',
 '<glossary_id=99781>',
 '<glossary_id=99782>',
 '<glossary_id=99783>',
 '<glossary_id=99784>',
 '<glossary_id=99785>',
 '<glossary_id=99786>',
 '<glossary_id=99787>',
 '<glossary_id=99788>',
 '<glossary_id=99789>',
 '<glossary_id=99790>',
 '<glossary_id=99791>',
 '<glossary_id=99792>',
 '<glossary_id=99793>',
 '<glossary_id=99794>',
 '<glossary_id=99795>',
 '<glossary_id=99796>',
 '<glossary_id=99797>',
 '<glossary_id=99798>',
 '<glossary_id=99799>',
 '<glossary_id=99800>',
 '<glossary_id=99801>',
 '<glossary_id=99802>',
 '<glossary_id=99803>',
 '<glossary_id=99804>',
 '<glossary_id=99805>',
 '<glossary_id=99806>',
 '<glossary_id=99807>',
 '<glossary_id=99808>',
 '<glossary_id=99809>',
 '<glossary_id=99810>',
 '<glossary_id=99811>',
 '<glossary_id=99812>',
 '<glossary_id=99813>',
 '<glossary_id=99814>',
 '<glossary_id=99815>',
 '<glossary_id=99816>',
 '<glossary_id=99817>',
 '<glossary_id=99818>',
 '<glossary_id=99819>',
 '<glossary_id=99820>',
 '<glossary_id=99821>',
 '<glossary_id=99822>',
 '<glossary_id=99823>',
 '<glossary_id=99824>',
 '<glossary_id=99825>',
 '<glossary_id=99826>',
 '<glossary_id=99827>',
 '<glossary_id=99828>',
 '<glossary_id=99829>',
 '<glossary_id=99830>',
 '<glossary_id=99831>',
 '<glossary_id=99832>',
 '<glossary_id=99833>',
 '<glossary_id=92045>',
 '<glossary_id=99835>',
 '<glossary_id=99836>',
 '<glossary_id=99837>',
 '<glossary_id=99838>',
 '<glossary_id=99839>',
 '<glossary_id=99840>',
 '<glossary_id=63785>',
 '<glossary_id=99842>',
 '<glossary_id=99843>',
 '<glossary_id=99844>',
 '<glossary_id=99845>',
 '<glossary_id=6298>',
 '<glossary_id=99847>',
 '<glossary_id=99848>',
 '<glossary_id=99849>',
 '<glossary_id=95126>',
 '<glossary_id=99851>',
 '<glossary_id=96662>',
 '<glossary_id=99853>',
 '<glossary_id=99854>',
 '<glossary_id=99855>',
 '<glossary_id=99856>',
 '<glossary_id=99857>',
 '<glossary_id=99858>',
 '<glossary_id=99859>',
 '<glossary_id=99860>',
 '<glossary_id=99861>',
 '<glossary_id=99862>',
 '<glossary_id=99863>',
 '<glossary_id=99864>',
 '<glossary_id=99865>',
 '<glossary_id=99866>',
 '<glossary_id=99867>',
 '<glossary_id=99868>',
 '<glossary_id=99869>',
 '<glossary_id=99870>',
 '<glossary_id=99871>',
 '<glossary_id=99872>',
 '<glossary_id=99873>',
 '<glossary_id=99874>',
 '<glossary_id=99875>',
 '<glossary_id=99876>',
 '<glossary_id=99877>',
 '<glossary_id=99878>',
 '<glossary_id=99879>',
 '<glossary_id=99880>',
 '<glossary_id=99881>',
 '<glossary_id=99882>',
 '<glossary_id=99883>',
 '<glossary_id=99884>',
 '<glossary_id=99885>',
 '<glossary_id=99886>',
 '<glossary_id=99887>',
 '<glossary_id=99888>',
 '<glossary_id=99889>',
 '<glossary_id=99890>',
 '<glossary_id=99891>',
 '<glossary_id=99892>',
 '<glossary_id=99893>',
 '<glossary_id=99894>',
 '<glossary_id=99895>',
 '<glossary_id=99896>',
 '<glossary_id=99897>',
 '<glossary_id=99898>',
 '<glossary_id=99899>',
 '<glossary_id=99900>',
 '<glossary_id=99901>',
 '<glossary_id=99902>',
 '<glossary_id=99903>',
 '<glossary_id=99904>',
 '<glossary_id=99905>',
 '<glossary_id=99906>',
 '<glossary_id=89600>',
 '<glossary_id=99908>',
 '<glossary_id=99909>',
 '<glossary_id=111103>',
 '<glossary_id=99911>',
 '<glossary_id=99912>',
 '<glossary_id=99913>',
 '<glossary_id=99914>',
 '<glossary_id=99915>',
 '<glossary_id=99916>',
 '<glossary_id=99917>',
 '<glossary_id=99918>',
 '<glossary_id=99919>',
 '<glossary_id=99920>',
 '<glossary_id=99921>',
 '<glossary_id=99922>',
 '<glossary_id=99923>',
 '<glossary_id=99924>',
 '<glossary_id=99925>',
 '<glossary_id=99926>',
 '<glossary_id=99927>',
 '<glossary_id=99928>',
 '<glossary_id=99929>',
 '<glossary_id=99930>',
 '<glossary_id=99931>',
 '<glossary_id=99932>',
 '<glossary_id=99933>',
 '<glossary_id=99934>',
 '<glossary_id=99935>',
 '<glossary_id=62339>',
 '<glossary_id=99937>',
 '<glossary_id=99938>',
 '<glossary_id=99939>',
 '<glossary_id=99940>',
 '<glossary_id=21652>',
 '<glossary_id=99942>',
 '<glossary_id=99943>',
 '<glossary_id=99944>',
 '<glossary_id=99945>',
 '<glossary_id=99946>',
 '<glossary_id=99947>',
 '<glossary_id=99948>',
 '<glossary_id=88997>',
 '<glossary_id=99950>',
 '<glossary_id=99951>',
 '<glossary_id=99952>',
 '<glossary_id=3401>',
 '<glossary_id=99954>',
 '<glossary_id=99955>',
 '<glossary_id=99956>',
 '<glossary_id=99957>',
 '<glossary_id=99958>',
 '<glossary_id=99959>',
 '<glossary_id=99960>',
 '<glossary_id=99961>',
 '<glossary_id=99962>',
 '<glossary_id=99963>',
 '<glossary_id=99964>',
 '<glossary_id=99965>',
 '<glossary_id=99966>',
 '<glossary_id=99967>',
 '<glossary_id=99968>',
 '<glossary_id=94738>',
 '<glossary_id=99970>',
 '<glossary_id=99971>',
 '<glossary_id=99972>',
 '<glossary_id=99973>',
 '<glossary_id=99974>',
 '<glossary_id=99975>',
 '<glossary_id=99976>',
 '<glossary_id=99977>',
 '<glossary_id=99978>',
 '<glossary_id=99979>',
 '<glossary_id=99980>',
 '<glossary_id=99981>',
 '<glossary_id=99982>',
 '<glossary_id=99983>',
 '<glossary_id=99984>',
 '<glossary_id=99985>',
 '<glossary_id=99986>',
 '<glossary_id=99987>',
 '<glossary_id=99988>',
 '<glossary_id=99989>',
 '<glossary_id=99990>',
 '<glossary_id=99991>',
 '<glossary_id=99992>',
 '<glossary_id=99993>',
 '<glossary_id=99994>',
 '<glossary_id=99995>',
 '<glossary_id=99996>',
 '<glossary_id=99997>',
 '<glossary_id=99998>',
 '<glossary_id=99999>',
 '<glossary_id=100000>',
 '<glossary_id=100001>',
 '<glossary_id=100002>',
 '<glossary_id=100003>',
 '<glossary_id=100004>',
 '<glossary_id=100005>',
 '<glossary_id=100006>',
 '<glossary_id=100007>',
 '<glossary_id=100008>',
 '<glossary_id=100009>',
 '<glossary_id=100010>',
 '<glossary_id=100011>',
 '<glossary_id=100012>',
 '<glossary_id=100013>',
 '<glossary_id=100014>',
 '<glossary_id=100015>',
 '<glossary_id=100016>',
 '<glossary_id=100017>',
 '<glossary_id=100018>',
 '<glossary_id=100019>',
 '<glossary_id=94927>',
 '<glossary_id=100021>',
 '<glossary_id=100022>',
 '<glossary_id=100023>',
 '<glossary_id=100024>',
 '<glossary_id=100025>',
 '<glossary_id=100026>',
 '<glossary_id=100027>',
 '<glossary_id=100028>',
 '<glossary_id=100029>',
 '<glossary_id=100030>',
 '<glossary_id=100031>',
 '<glossary_id=100032>',
 '<glossary_id=100033>',
 '<glossary_id=100034>',
 '<glossary_id=100035>',
 '<glossary_id=100036>',
 '<glossary_id=100037>',
 '<glossary_id=100038>',
 '<glossary_id=100039>',
 '<glossary_id=100040>',
 '<glossary_id=100041>',
 '<glossary_id=100042>',
 '<glossary_id=100043>',
 '<glossary_id=100044>',
 '<glossary_id=100045>',
 '<glossary_id=100046>',
 '<glossary_id=100047>',
 '<glossary_id=100048>',
 '<glossary_id=100049>',
 '<glossary_id=100050>',
 '<glossary_id=100051>',
 '<glossary_id=100052>',
 '<glossary_id=100053>',
 '<glossary_id=100054>',
 '<glossary_id=100055>',
 '<glossary_id=31391>',
 '<glossary_id=100057>',
 '<glossary_id=100058>',
 '<glossary_id=100059>',
 '<glossary_id=100060>',
 '<glossary_id=100061>',
 '<glossary_id=100062>',
 '<glossary_id=100063>',
 '<glossary_id=100064>',
 '<glossary_id=100065>',
 '<glossary_id=100066>',
 '<glossary_id=100067>',
 '<glossary_id=100068>',
 '<glossary_id=100069>',
 '<glossary_id=100070>',
 '<glossary_id=100071>',
 '<glossary_id=100072>',
 '<glossary_id=100073>',
 '<glossary_id=100074>',
 '<glossary_id=100075>',
 '<glossary_id=100076>',
 '<glossary_id=100077>',
 '<glossary_id=100078>',
 '<glossary_id=100079>',
 '<glossary_id=100080>',
 '<glossary_id=100081>',
 '<glossary_id=100082>',
 '<glossary_id=100083>',
 '<glossary_id=100084>',
 '<glossary_id=100085>',
 '<glossary_id=100086>',
 '<glossary_id=100087>',
 '<glossary_id=100088>',
 '<glossary_id=100089>',
 '<glossary_id=100090>',
 '<glossary_id=100091>',
 '<glossary_id=100092>',
 '<glossary_id=100093>',
 '<glossary_id=100094>',
 '<glossary_id=100095>',
 '<glossary_id=100096>',
 '<glossary_id=100097>',
 '<glossary_id=100098>',
 '<glossary_id=100099>',
 '<glossary_id=100100>',
 '<glossary_id=100101>',
 '<glossary_id=1236>',
 '<glossary_id=100103>',
 '<glossary_id=100104>',
 '<glossary_id=100105>',
 '<glossary_id=100106>',
 '<glossary_id=100107>',
 '<glossary_id=100108>',
 '<glossary_id=100109>',
 '<glossary_id=100110>',
 '<glossary_id=100111>',
 '<glossary_id=100112>',
 '<glossary_id=100113>',
 '<glossary_id=100114>',
 '<glossary_id=100115>',
 '<glossary_id=100116>',
 '<glossary_id=100117>',
 '<glossary_id=100118>',
 '<glossary_id=100119>',
 '<glossary_id=100120>',
 '<glossary_id=100121>',
 '<glossary_id=100122>',
 '<glossary_id=100123>',
 '<glossary_id=100124>',
 '<glossary_id=100125>',
 '<glossary_id=100126>',
 '<glossary_id=100127>',
 '<glossary_id=100128>',
 '<glossary_id=100129>',
 '<glossary_id=100130>',
 '<glossary_id=100131>',
 '<glossary_id=100132>',
 '<glossary_id=100133>',
 '<glossary_id=100134>',
 '<glossary_id=100135>',
 '<glossary_id=100136>',
 '<glossary_id=100137>',
 '<glossary_id=100138>',
 '<glossary_id=100139>',
 '<glossary_id=100140>',
 '<glossary_id=100141>',
 '<glossary_id=100142>',
 '<glossary_id=100143>',
 '<glossary_id=100144>',
 '<glossary_id=100145>',
 '<glossary_id=100146>',
 '<glossary_id=100147>',
 '<glossary_id=100148>',
 '<glossary_id=100149>',
 '<glossary_id=100150>',
 '<glossary_id=100151>',
 '<glossary_id=100152>',
 '<glossary_id=100153>',
 '<glossary_id=100154>',
 '<glossary_id=100155>',
 '<glossary_id=100156>',
 '<glossary_id=100157>',
 '<glossary_id=100158>',
 '<glossary_id=100159>',
 '<glossary_id=100160>',
 '<glossary_id=100161>',
 '<glossary_id=100162>',
 '<glossary_id=100163>',
 '<glossary_id=100164>',
 '<glossary_id=100165>',
 '<glossary_id=100166>',
 '<glossary_id=100167>',
 '<glossary_id=100168>',
 '<glossary_id=100169>',
 '<glossary_id=100170>',
 '<glossary_id=100171>',
 '<glossary_id=100172>',
 '<glossary_id=100173>',
 '<glossary_id=100174>',
 '<glossary_id=100175>',
 '<glossary_id=100176>',
 '<glossary_id=100177>',
 '<glossary_id=100178>',
 '<glossary_id=100179>',
 '<glossary_id=100180>',
 '<glossary_id=100181>',
 '<glossary_id=100182>',
 '<glossary_id=100183>',
 '<glossary_id=100184>',
 '<glossary_id=100185>',
 '<glossary_id=100186>',
 '<glossary_id=100187>',
 '<glossary_id=100188>',
 '<glossary_id=100189>',
 '<glossary_id=100190>',
 '<glossary_id=100191>',
 '<glossary_id=100192>',
 '<glossary_id=100193>',
 '<glossary_id=100194>',
 '<glossary_id=100195>',
 '<glossary_id=100196>',
 '<glossary_id=100197>',
 '<glossary_id=100198>',
 '<glossary_id=100199>',
 '<glossary_id=100200>',
 '<glossary_id=100201>',
 '<glossary_id=100202>',
 '<glossary_id=100203>',
 '<glossary_id=100204>',
 '<glossary_id=100205>',
 '<glossary_id=100206>',
 '<glossary_id=100207>',
 '<glossary_id=100208>',
 '<glossary_id=100209>',
 '<glossary_id=62699>',
 '<glossary_id=100211>',
 '<glossary_id=100212>',
 '<glossary_id=100213>',
 '<glossary_id=100214>',
 '<glossary_id=100215>',
 '<glossary_id=100216>',
 '<glossary_id=100217>',
 '<glossary_id=100218>',
 '<glossary_id=100219>',

In [9]:
import re

for index in range(len(translated_text)):
    temp = translated_text[index]
    glossary_ids = [int(glossary_id) for glossary_id in re.findall(r"<glossary_id=(\d+)>", temp)]
    for glossary_id in glossary_ids:
        temp = temp.replace("<glossary_id={0}>".format(glossary_id), glossary_dict[glossary_id]["ko"])
    translated_text[index] = temp
translated_text

['거궐',
 '대궐',
 '천문',
 '잠룡',
 '군룡',
 '천룡',
 '창웅',
 '제도',
 '만리',
 '파천',
 '노도',
 '주안',
 '봉난',
 '용전',
 '봉화',
 '능운',
 '신무',
 '구천',
 '곤붕',
 '경천',
 '불패',
 '영요',
 '허요',
 '괴요',
 '유미',
 '육미',
 '구미',
 '몽주',
 '섭혼',
 '홍안',
 '서화',
 '소혼',
 '탈속세',
 '귀홍',
 '예생',
 '앵주',
 '야담',
 '월화',
 '정화',
 '멸혼',
 '불요',
 '예영',
 '경영',
 '절영',
 '고성',
 '역성',
 '좌성',
 '신장',
 '연홍',
 '은신',
 '천라',
 '왕류',
 '절경',
 '매익',
 '붕습',
 '석양',
 '탐랑',
 '안월',
 '주악',
 '일광',
 '무외',
 '함광',
 '산광',
 '복광',
 '궁천',
 '경천',
 '황천',
 '천야',
 '태양',
 '호기',
 '천가',
 '경성',
 '금오',
 '적일',
 '고리',
 '낙명',
 '여명',
 '천성',
 '위곤',
 '형양',
 '법신',
 '요황의 회랑',
 '신수대',
 '제왕비경',
 '성왕검굴',
 '지선유적',
 '벽사산장',
 '장착',
 '선호 아이템',
 '살의치',
 '패션점수',
 '천명석',
 '천공석',
 '분노',
 '진급',
 '영기',
 '장신구',
 '희귀',
 '영웅',
 '전설',
 '궁극기',
 '보물찾기',
 '광야전장',
 '신옥유적',
 '만상서원',
 '최고급 보물찾기',
 '흉노전',
 '개천부',
 '천옹성',
 '불량한 선비',
 '영롱탑',
 '영강',
 '영혼등잔',
 '운환',
 '초월',
 '성신소인',
 '모집',
 '일일이벤트',
 '한정 이벤트',
 '기념일 이벤트',
 '버서커',
 '여우혼',
 '무신',
 '어검',
 '홍풍',
 '영설',
 '황풍',
 '천추',
 '홍안',
 '백설',
 '성전',
 '매람',
 '백룡',
 '묵영',
 '뇌정',
 '공작',
 '뇌신',
 '화전',
 '사이버펑크',
 '교복',
 '수영복',
 '밸런타인데이',
 '푸른깃털',
 '토로로',
 '금을 삼킨 현웅',
 '곤',
 '송어',
 '현무',
 '패왕룡',
 '로봇',
 '제청원성',
 '화염성수',
 '칠성검',
 '옥정병',
 '혼돈우산',
 '풍화륜',
 '영매방울',
 '호천탑',
 '태극도',
 '타신편',
 '혼천릉',
 '금강탁',
 '여와석',
 '동황종',
 '건곤계',
 '곤륜경',
 '공동인',
 '묵호',
 '기병괴뢰',
 '마화된 영소',
 '성승',
 '고기 한 그릇',
 '사탕상자',
 '빨간팀 수정',
 '파란팀 수정',
 '중립 깃발',
 '빨간팀 깃발',
 '파란팀 깃발',
 '전송문턱',
 '천부영군',
 '규목사수',
 '육귀요왕',
 '청봉둔갑',
 '고상한 요희',
 '서적을 든 산선',
 '천뢰요사',
 '금린전사',
 '천금공주(동료)',
 '신진선사',
 '무외',
 '천우공주',
 '마연신왕',
 '흑비비',
 '흑화된 투사',
 '흑화된 영체',
 '사교',
 '수라귀사',
 '액운영주',
 '오령',
 '흑화된 공황귀',
 '흑화된 마령',
 '보류',
 '액살학도',
 '액살교관',
 '중매쟁이',
 '무녀',
 '음영',
 '절세검역',
 '천수불타',
 '진환의 눈동자',
 '시간의 강',
 '빛의 신',
 '마신의 몸',
 '공간의 문',
 '생명나무',
 '건천의 주인',
 '흑화된 빙령',
 '화염뿔 영왕',
 '회전거북',
 '육귀',
 '낭환천서',
 '신계전사',
 '흑화된 호위병',
 '양곡',
 '회춘감실',
 '마화된 방홍',
 '소형 밀실',
 '황금성제',
 '수호자',
 '시련괴뢰',
 '신경비보',
 '주작영왕',
 '영왕',
 '빙한염라',
 '단련장로',
 '전직',
 '자라',
 '진무선왕',
 '刺灵',
 '백궤선왕',
 '사석',
 '혼병',
 '서리도깨비',
 '장손',
 '적쟁선왕',
 '호수신령',
 '복파선왕',
 '미친오소리',
 '화염여우',
 '성우선왕',
 '독창포',
 '순소선왕',
 '요괴시종',
 '통비선왕',
 '벌레선비',
 '벌레병사',
 '야심마전',
 '소원',
 '옥형선왕',
 '고목신령',
 '검자',
 '검생',
 '검도',
 '인리',
 '청염영왕',
 '물귀신',
 '초조선왕',
 '상군',
 '장신',
 '수사선왕',
 '용마',
 '만인선왕',
 '바람송골매',
 '단원선왕',
 '요안',
 '현혹귀',
 '현혹기둥',
 '용암장사',
 '지옥염라',
 '바다요괴',
 '혼갑상자',
 '미혹인형',
 '미혹괴',
 '미혹귀',
 '수련명룡',
 '서리혼',
 '액매염라',
 '공생마전',
 '상화염라',
 '난겁탑',
 '난겁탑-바닥',
 '음뢰염라',
 '자폭괴뢰',
 '상전염라',
 '사령역사',
 '암봉염라',
 '세이렌',
 '바다요괴상자',
 '유령병',
 '유령불',
 '유혼',
 '연꽃봉황',
 '빙혼',
 '상한염라',
 '명뢰탑',
 '정창염라',
 '자폭인형',
 '광전사염라',
 '자금령',
 '명반',
 '적호영수',
 '현랑영수',
 '마호영왕',
 '기린영왕',
 '태양용암석상',
 '태양초령',
 '등불괴물',
 '태양화매',
 '태양가시괴',
 '태양나무정령',
 '태음흉사',
 '태음기병',
 '백부정예',
 '태음선봉',
 '태음마장',
 '황성수위병',
 '혼돈칼잡이',
 '화요',
 '혼돈사무라이',
 '혼돈용사',
 '혼돈검혼',
 '황금문양비석',
 '미스릴문양비석',
 '자객',
 '용검',
 '어린도사',
 '복산자',
 '소소',
 '토사자',
 '꼭두각시인형',
 '정곡은사',
 '현요영수',
 '성문 호위관',
 '기관사자',
 '수호교룡',
 '묵우사형',
 '약릉사저',
 '시련장로',
 '천옹성 수위병',
 '홍릉',
 '빙령궁주',
 '제익',
 '객잔 여주인',
 '행상인',
 '종가장사',
 '천검종 검자',
 '천검종 장로',
 '곤장로',
 '건원성녀',
 '건장로',
 '함몰기관',
 '수요',
 '흑화된 무승',
 '흑화된 부령',
 '재앙매',
 '황혼',
 '흉랑',
 '성문 수위병',
 '방패거북',
 '흑화된 살수',
 '왕가 제자',
 '숲의 화요',
 '암흑요괴족',
 '운소맹원',
 '흑화된 영족',
 '제성학원 학생',
 '마화된 학생',
 '마화된 정예학생',
 '방가지킴이',
 '동양외문 제자',
 '흑화된 참가자',
 '비행도적',
 '동양 참가 제자',
 '액운흉령',
 '창원괴수',
 '함석영수',
 '사라진 영체',
 '시공원소',
 '흑화된 수궁전사',
 '흑화된 수궁장수',
 '창왕궁 괴뢰',
 '혼란괴뢰',
 '흑화된 심마',
 '투전성족',
 '흑화된 무사',
 '무레한 수사',
 '천검종 제자',
 '미친 영검',
 '형벌제자',
 '흑화된 검마',
 '흑화된 정예 핵심 제자',
 '빙원늑대',
 '빙궁전사',
 '수궁정예',
 '진의 염령',
 '난공 방랑자',
 '위장살수',
 '자색옷 사도',
 '기형마물',
 '변이된 건원제자',
 '실성한 주민',
 '흑화된 마괴',
 '숲의 영호',
 '혼돈수위병',
 '혼돈올빼미',
 '혼돈혈랑',
 '탈영천병',
 '실성한 신민',
 '혼란신녀',
 '혼돈조물',
 '절신천 오랑캐',
 '혼란빙령',
 '허공검령',
 '왜곡된 나무정령',
 '부서진 용암석상',
 '실성한 정예의 혼',
 '갈택교 교도',
 '고목교 교도',
 '선국 폭도',
 '장청 반란군',
 '반역사사',
 '정예혼돈자객',
 '혼돈마격',
 '태고시위',
 '혼돈요혼',
 '혼돈원소',
 '백전',
 '치관',
 '궁기',
 '유명여신',
 '허공마주',
 '남황택아',
 '구양효생',
 '천산눈정령',
 '단신마랑',
 '백호',
 '요인',
 '주작 추격자',
 '화염새',
 '약환',
 '연수',
 '천 년 나무요괴',
 '백호대도',
 '유암',
 '소멸',
 '허공의 힘',
 '화령',
 '정예·접선',
 '재앙원소',
 '재앙괴뢰',
 '재앙부령',
 '재앙마령',
 '재앙흉랑',
 '재앙석마',
 '흑령귀사',
 '흑령괴뢰',
 '흑령시녀',
 '흑령마호',
 '흑령서리늑대',
 '흑령마사',
 '흑화된 도깨비',
 '흑화된 광기',
 '흑화된 영혼',
 '흑화된 경직',
 '흑화된 공포',
 '흑화된 분노',
 '서수 기린',
 '영탑',
 '마화된 방홍',
 '흑화된 검시',
 '흑화된 광도',
 '흑화된 장사',
 '백발 야만족',
 '비술괴뢰',
 '칼날올빼미',
 '혈조랑',
 '독니거미',
 '흑화된 검주',
 '흑화된 광전사',
 '흑화된 인마',
 '흑발상투 사령',
 '비술빙마',
 '매 조련사',
 '탐혼괴수',
 '액운석령',
 '사악한 검사',
 '실성한 전사',
 '가면사령',
 '야만의 주인',
 '괴뢰여왕',
 '용암핵괴수',
 '액운마귀',
 '자폭원소',
 '원양해적',
 '심연천민',
 '선경화요',
 '선경방랑자',
 '영봉',
 '허무여제',
 '흑화된 화요',
 '장검종 반역자-여',
 '선인',
 '비무대 괴뢰',
 '변이제자',
 '정예·거대어검',
 '정예·마장수',
 '원주민',
 '작은 버섯',
 '설녀',
 '요랑',
 '보검괴뢰',
 '어령괴뢰',
 '어천용장',
 '만상천주',
 '시공의 천마',
 '시공의 지살',
 '시공의 요령',
 '시공의 잔혼',
 '선령석',
 '우현결정',
 '성령초',
 '길조상자',
 '금상자',
 '은상자',
 '천계수위병',
 '영계수위병',
 '천계 감독관',
 '영계 감독관',
 '산장 호위병',
 '수위병장',
 '천명',
 '백안',
 '흡혈신병',
 '초천교',
 '운요전부',
 '검',
 '운해병사',
 '춘각시녀',
 '비염마후',
 '굴풍검비',
 '소용돌이',
 '황야 조련사',
 '황야 전투신수',
 '마병',
 '무한한 도겁주',
 '은신괴',
 '화염술사',
 '혈검',
 '마사',
 '화원소',
 '액운염마',
 '현황살수',
 '고독한 잔혼',
 '탐천수족',
 '황야의 원혼',
 '불멸의 시녀',
 '불멸의 령',
 '명월환영',
 '월신잔영',
 '천굴수위병',
 '여명의 의지',
 '고대마족',
 '마연의 혼',
 '요족정예',
 '옥면서생',
 '무군유지',
 '빙의인형',
 '황천괴뢰',
 '이화수위병',
 '이화마군',
 '음영검사',
 '음영검주',
 '용암천호',
 '난마수주',
 '난공부적수위',
 '난공부적주인',
 '자혼녀',
 '천마창주',
 '허명빙마',
 '살육천주',
 '신해수하',
 '성린신주',
 '범천빙령',
 '무한천주',
 '검온선사',
 '벽락선사',
 '영인선사',
 '황천선사',
 '궁지보주',
 '지옥무승',
 '금단계주',
 '천기황혼',
 '천기황주',
 '밀림검영',
 '숲 속 은둔자',
 '마화된 태백',
 '혼란수령',
 '미혹된 검요',
 '미친 궁기',
 '백록의 매영',
 '운림요괴여우',
 '운림숲요괴',
 '삼라창왕',
 '정주호위병',
 '정주검선',
 '정주괴수',
 '배은망덕한 마군',
 '청구숲요괴',
 '청구술사',
 '청구 수위병',
 '물리의 매영',
 '수구이족',
 '수구악마',
 '마신의 령',
 '이계꽃요괴',
 '숲의 주인',
 '물리의 흑혼',
 '어둠영체',
 '허명부주',
 '저승의 주인',
 '유염호위병',
 '유염석요괴',
 '화염의 주인',
 '방녕마군',
 '허령호위병',
 '허령괴뢰',
 '허령의 주인',
 '마화된 미음주민',
 '미음마괴',
 '음유창왕',
 '탐랑의 매영',
 '등불석영',
 '등불사령',
 '등불괴뢰',
 '화염석괴',
 '화염괴뢰',
 '염화전사',
 '탐랑의 흑혼',
 '상월의 여인',
 '상월성검',
 '염월마사',
 '유월화령',
 '유월선녀',
 '사악한 칼잡이',
 '화두마군',
 '갇힌 백록',
 '갇힌 물리',
 '갇힌 탐랑',
 '창영',
 '상어',
 '결혼',
 '멸망의 군차',
 '기계대붕',
 '라마',
 '식령매',
 '구황법사',
 '저주받은 인수',
 '혼원영산',
 '태극보물지도',
 '만상천의',
 '풍화신륜',
 '자웅쌍검',
 '칠성도',
 '옥정선병',
 '영롱보탑',
 '금강옥',
 '혼돈무사',
 '혼돈신도',
 '혼돈선수',
 '보스·사교',
 '혼돈자객',
 '혼돈인수',
 '혼돈살수',
 '보스·낙운소',
 '액운의 검백',
 '액운의 무사',
 '액운의 선비',
 '보스·초람',
 '액운의 산고양이',
 '액운의 거미',
 '액운의 나무요괴',
 '보스·초진',
 '삼림마령',
 '운소맹 제자',
 '운소맹 정예',
 '보스·낙구성',
 '동양검객',
 '동양도부수',
 '동양검호',
 '보스·방홍',
 '청의',
 '귀면',
 '혈참',
 '보스·왕염',
 '냉봉',
 '은창',
 '무명',
 '보스·태백',
 '구미호',
 '통혼늑대',
 '보스·수후',
 '빙릉요괴',
 '음석요괴',
 '철산요괴',
 '보스·요주',
 '영혼수색자',
 '영혼통제자',
 '도겁사',
 '보스·사명장로',
 '자영사',
 '분리사',
 '멸생사',
 '보스·윤회장로',
 '허공검혼',
 '변이시체',
 '실성한 외다리',
 '보스·뇌뢰창천존',
 '독니요괴묘',
 '거대독거미',
 '가시고목령',
 '보스·화염검천존',
 '난공요령',
 '난공검객',
 '남공장로',
 '보스·난공성주',
 '배액검치',
 '배액괴수',
 '배액검사',
 '보스·배액교주',
 '구황괴면',
 '구황수라',
 '보스·구황친왕',
 '삼라검사',
 '삼라은사',
 '보스·삼라신선',
 '요신산 여우',
 '요신산 늑대',
 '요신산 매',
 '보스·영혼감금신',
 '천굴빙백',
 '천굴석령',
 '천굴단조괴',
 '보스·천굴액령',
 '승복천관',
 '정화복천관',
 '송곳눈천관',
 '보스·염라천왕',
 '자결천관',
 '정예천관',
 '멸망천관',
 '보스·명광천왕',
 '미공검령',
 '미지마령',
 '미득소령',
 '보스·신정미륵',
 '미신시령',
 '미사주령',
 '미신목령',
 '보스·작염미륵',
 '형목성관',
 '형금성관',
 '형수성관',
 '보스·태양징벌군주',
 '형화성관',
 '형토성관',
 '감형성관',
 '보스·명월징벌군주',
 '살육법사',
 '은신귀면',
 '절선수라',
 '보스·주선천왕',
 '살육검사',
 '은신창왕',
 '절선은사',
 '보스·주선영왕',
 '제천신선여우',
 '제천영혼늑대',
 '제천매',
 '보스·제천마후',
 '석천빙백',
 '석천석령',
 '석천단조마괴',
 '보스·석쳔마신',
 '문양탑 모형',
 '직혼창',
 '헌원창',
 '원소신병',
 '원초고령',
 '양의황령',
 '삼청성령',
 '사상왕령',
 '오행법령',
 '육도마령',
 '칠계선령',
 '팔황부령',
 '구전신령',
 '천기황령',
 '지령성령',
 '현심왕령',
 '황도법령',
 '태상마령',
 '고역선령',
 '홍애부령',
 '황룡신령',
 '매지션',
 '신역패주',
 '군림천하',
 '천하무쌍',
 '월장공',
 '주검혼',
 '병아리 런',
 '병아리',
 '전투닭',
 '송골매환영',
 '대형 마력수정',
 '소형 마력수정',
 '신경정예',
 '신전성녀',
 '괴뢰거인',
 '제의',
 '천형',
 '소혁',
 '종리',
 '임풍',
 '마비안',
 '극액영왕',
 '관일금붕',
 '파쇄영주',
 '탈천노마',
 '운몽령',
 '주작',
 '청홍장로',
 '남황공봉',
 '적염호왕',
 '묘요용사',
 '탈것늑대',
 '혈염마왕',
 '화운도인',
 '용암용수',
 '화염진령',
 '업화마랑',
 '화염마녀',
 '혼련선자',
 '남황조봉',
 '육귀요황',
 '영호여제',
 '탈것호랑이',
 '행인마사',
 '만고마사',
 '어룡마사',
 '천마사',
 '재결마사',
 '암흑마사',
 '성마사',
 '마주사자',
 '방홍',
 '귀혼마사',
 '혈동마사',
 '강철마사',
 '장정마사',
 '개산마사',
 '사령문양 마호',
 '사령눈 마랑',
 '사령검 마군',
 '사령날개 마군',
 '사령영매 마군',
 '용각요왕',
 '사각요왕',
 '흡성요앙',
 '단성요왕',
 '재앙기린',
 '사명마후',
 '형천마제',
 '외눈마제',
 '제홍마조',
 '도겁용조',
 '음혼마장',
 '열혼마존',
 '살혼마왕',
 '묘비',
 '가속',
 'HP회복',
 '버섯',
 '폭탄',
 '소환',
 '마그마',
 '얼음 봉인',
 '미스릴괴뢰',
 '순금괴뢰',
 '영석괴뢰',
 '흑화된 판도라',
 '해상요괴',
 '운해화요',
 '운해고목령',
 '흑화된 백탁',
 '금고 수위병',
 '금고 정예수위병',
 '금화 수위병',
 '금화 장수',
 '보석 수위병',
 '보석 장수',
 '금화광석',
 '보석광석',
 '재운을 비루는 비휴',
 '도적 두목',
 '창고 도적',
 '신왕영황',
 '신옥요괴',
 '옥핵괴뢰',
 '거대주먹',
 '탈혼거대주먹',
 '청봉',
 '녹기',
 '천계수위병·풍',
 '천계수위병·림',
 '천계수위병·화',
 '천계수위병·산',
 '영계수위병·풍',
 '영계수위병·림',
 '영계수위병·화',
 '영계수위병·산',
 '광수의 습격',
 '광수의 위엄',
 '광수신속보호',
 '제왕의 힘',
 '제왕군위',
 '제왕신속보호',
 '요황의 수호',
 '요황위엄',
 '요황신속보호',
 '성왕의 숨',
 '성왕의 위엄',
 '성왕통치',
 '지선의 령',
 '지선의 위엄',
 '지선통칭',
 '만불의 불멸',
 '만불신위',
 '만불어법',
 '신왕의 분노',
 '신왕의 권위',
 '신왕의 어극',
 '먹구름',
 '요괴의 춤',
 '푸른 서리',
 '떠오르는 해',
 '만역의 위력',
 '만역의 광휘',
 '만역의 성광',
 '만역의 도화',
 '눈부신 별조각',
 '은빛 운치',
 '달에 가린 슬픔',
 '고독한 밤빛',
 '천공의 문',
 '우아한 구름',
 '찰나의 찬란',
 '형벌의 깃털',
 '초야의 왕',
 '빛나는 밤하늘',
 '구름에 가린 달',
 '은빛 은하',
 '하늘길',
 '달과 구름',
 '그림자 별',
 '태상망정',
 '금슬화명',
 '금궐경루',
 '난새의 소리',
 '요란한 천둥',
 '공허와 고요',
 '열혈 운동위원회',
 '캠퍼스 퀸',
 '공부벌레',
 '슈퍼 신입생',
 '비치파티',
 '뮤직플레이',
 '우아한 신사',
 '로맨틱스위트',
 '관용의 귀족',
 '연애달인',
 '금빛 눈동자',
 '천자의 깃',
 '그림자빛',
 '흐르는 불빛',
 '빛나는 별빛',
 '백전걸상',
 '피타고라스 정리',
 '주문제작 컴퍼스',
 '강필 서예']

In [10]:
df_compare = pd.DataFrame({
    "reference": reference,
    "translation": translation,
    "translated": translated_text,
})
df_compare

    reference translation translated
0          巨阙          거궐         거궐
1          帝阙          대궐         대궐
2          天阙          천문         천문
3          潜龙          잠룡         잠룡
4          战龙          군룡         군룡
..        ...         ...        ...
995      煌天星彩      빛나는 별빛     빛나는 별빛
996      百战折凳        백전걸상       백전걸상
997      勾股定理    피타고라스 정리   피타고라스 정리
998      定制圆规    주문제작 컴퍼스   주문제작 컴퍼스
999      硬笔书法       강필 서예      강필 서예

[1000 rows x 3 columns]

In [11]:
df_compare.to_csv("translation_result.csv", index=False)