In [1]:
import pandas as pd

file_name = "translation_result_of_fine-tuned-models_nllb-200-distilled-600M_zh2ko_1025.csv"
df = pd.read_csv(file_name)
df

,source,references,candidates
0,2天22<start>小时<middle>시간<end>22分钟,2일 22<start>시간<end> 22분,2일 22 시간 22분
1,"{阿登丘陵的亚岱尔,找亚岱尔<start>交谈<middle>대화<end>,序章}","{아르덴 산맥의 아데어,아데어와 <start>대화<end>하기,프롤로그}","{아르덴 산맥의 아데어,아데어와 대화 하기,프롤로그}"
2,<start>神<middle>신<end>秘宝箱,<start>신<end>비상자,신 비한 보물상자
3,骑战装备熔炉<start>等级达到<middle>레벨 달성<end>4级,기마전투 장비 용로 4<start>레벨 달성<end>,기마전투 장비 용로 4 레벨 달성
4,<start>菜鸟<middle>신입<end>玉镯,<start>신입<end> 옥팔찌,신입 옥팔찌
...,...,...,...
6708,天谴之<start>地<middle>지<end>灵晶戒,천벌의 <start>지<end>령 수정반<start>지<end>,천벌의 지 령 수정반 지
6709,暗器图纸\n记载梵<start>天<middle>천<end>双轮制法的图纸，用于梵<sta...,암기 도면\n암기 범<start>천<end>쌍륜 합성 및 승품에 사용됩니다.,암기 도면\n암기 천 쌍륜 합성 및 승품에 사용됩니다.
6710,"{魔力之书（精通闪避Ⅱ）,使用后学会通用技能【精通闪避Ⅱ】,<start>制作<middle...","{지식의 서 (회피 마스터리 Ⅱ),사용 후, 공통의 스킬 【회피 마스터리 Ⅱ】를 습...","{지식의 서 (회피 마스터리 II),사용 후, 공통의 스킬 【 회피 마스터리 II】..."
6711,正在<start>收集<middle>수집<end>{0},현재 {0} <start>수집<end>,{0} 수집 중
6712,遇见一群疑似黑风会的<start>人<middle>사람<end>，什么情况？,흑풍회 <start>사람<end>으로 의신되는 <start>사람<end>들이 나타났...,흑풍회 사람 들을 만났습니다. 어떤 상황입니까?

In [2]:
import re

for index, row in df.iterrows():
    match = re.search("<start>(.*?)<middle>(.*?)<end>", row["source"])
    glossary_zh_CN = match.group(1)
    glossary_ko = match.group(2)
    if glossary_ko in row["candidates"]:
        df.at[index, "matched"] = 1
    else:
        df.at[index, "matched"] = 0

In [3]:
df.to_csv(file_name, index=False)
df

,source,references,candidates,matched
0,2天22<start>小时<middle>시간<end>22分钟,2일 22<start>시간<end> 22분,2일 22 시간 22분,1.0
1,"{阿登丘陵的亚岱尔,找亚岱尔<start>交谈<middle>대화<end>,序章}","{아르덴 산맥의 아데어,아데어와 <start>대화<end>하기,프롤로그}","{아르덴 산맥의 아데어,아데어와 대화 하기,프롤로그}",1.0
2,<start>神<middle>신<end>秘宝箱,<start>신<end>비상자,신 비한 보물상자,1.0
3,骑战装备熔炉<start>等级达到<middle>레벨 달성<end>4级,기마전투 장비 용로 4<start>레벨 달성<end>,기마전투 장비 용로 4 레벨 달성,1.0
4,<start>菜鸟<middle>신입<end>玉镯,<start>신입<end> 옥팔찌,신입 옥팔찌,1.0
...,...,...,...,...
6708,天谴之<start>地<middle>지<end>灵晶戒,천벌의 <start>지<end>령 수정반<start>지<end>,천벌의 지 령 수정반 지,1.0
6709,暗器图纸\n记载梵<start>天<middle>천<end>双轮制法的图纸，用于梵<sta...,암기 도면\n암기 범<start>천<end>쌍륜 합성 및 승품에 사용됩니다.,암기 도면\n암기 천 쌍륜 합성 및 승품에 사용됩니다.,1.0
6710,"{魔力之书（精通闪避Ⅱ）,使用后学会通用技能【精通闪避Ⅱ】,<start>制作<middle...","{지식의 서 (회피 마스터리 Ⅱ),사용 후, 공통의 스킬 【회피 마스터리 Ⅱ】를 습...","{지식의 서 (회피 마스터리 II),사용 후, 공통의 스킬 【 회피 마스터리 II】...",1.0
6711,正在<start>收集<middle>수집<end>{0},현재 {0} <start>수집<end>,{0} 수집 중,1.0
6712,遇见一群疑似黑风会的<start>人<middle>사람<end>，什么情况？,흑풍회 <start>사람<end>으로 의신되는 <start>사람<end>들이 나타났...,흑풍회 사람 들을 만났습니다. 어떤 상황입니까?,1.0